### ISSUE TITLE
Changing username

### ISSUE THREAD

**Issue by MrBungle71** [danpaulson/swgoh.gg.public#105]
My swgoh.gg username when copied and linked comes up as:
https://swgoh.gg/u/mr. bungle/
Due to my username being Mr. Bungle
This causes issues when linking the username in chat apps. Is there anyway to change the username to something more browser friendly? I.e. mrbungle
Thank you.

**Comment by Darthclem1** [comment]
I have excactly the same problem !
https://swgoh.gg/u/ujjvlvlrtrsem4pgiwrsqsng/ this isn't a browser friendly username...
I wish I could have something like "Darthclem1"
Thank you for helping us (and this fabulous website)

**Comment by danpaulson** [comment]
This functionality is now live.
