### ISSUE TITLE
Veteran Chuwi and Solo (amongst others) are not listed in Shipments

### ISSUE THREAD

**Issue by azgo** [danpaulson/swgoh.gg.public#108]
Veteran Chuwi and Solo changes to be available from Shipments are not reflected under swgoh "Shard Locations".
Basicly as I've looked over the https://swgoh.gg/db/shipments/ page they're quite outdated and Base shipments are not included at all.
A thorough update and include would be pretty nice!

**Comment by danpaulson** [comment]
At this time we're not able to get reliable data on this.
