### ISSUE TITLE
Unit Search returning 500 status code

### ISSUE THREAD

**Issue by fulento** [danpaulson/swgoh.gg.public#111]
Response code 500 from https://swgoh.gg/api/guilds/304/units/

This api call is returning 500s and our guild is no longer able to search units on https://swgoh.gg/g/304/ventress-moon/unit-search/. 

For full context I have used this api endpoint to scrape data recently (maybe too heavily for the last 2 weeks) but now once per day on a scheduled task. Are there rate limits or documentation for the the apis listed at https://swgoh.gg/api/?

**Comment by danpaulson** [comment]
This should be fixed now.
