### ISSUE TITLE
Deleting an account

### ISSUE THREAD

**Issue by danielan87** [danpaulson/swgoh.gg.public#114]
Hi,

Someone in my guild forgot his account so he created another one. Now our guild is 51/50:
https://swgoh.gg/g/27003/hogtown-knights/

Can you delete the out of date account for Locke? (the one with lower gp).
https://swgoh.gg/u/locke9/ <--- keep
https://swgoh.gg/u/locke5/ <--- delete

Thanks!

**Comment by danpaulson** [comment]
Deleted.
