### ISSUE TITLE
Collection score problem

### ISSUE THREAD

**Issue by Miky212** [danpaulson/swgoh.gg.public#118]
Greetings. While testing something out, I turned off "Enable Collection Score" in the Settings tab. After that, I logged out, to see if my collection truly didn't show, and it worked, but then I couldn't log in (shows Server Error 500). Does it have to do with the Collection Sync or is your server down? Thanks in advance.

My profile, if it helps: https://swgoh.gg/u/miky/

**Comment by danpaulson** [comment]
This should be resolved now. Let me know if that's not the case.

**Comment by Miky212** [comment]
It's working now, thanks. But is not showing my arena rank a side effect of that?

**Comment by danpaulson** [comment]
Yes - that should be resolved next auto-sync at your payout.
