### ISSUE TITLE
Ability Levels and Mods not loading for some characters

### ISSUE THREAD

**Issue by Cletus-swgoh** [danpaulson/swgoh.gg.public#119]
None of my characters show their ability levels and some also do not show their equipped mods. 
Here are several examples:
https://swgoh.gg/u/cletus/collection/238/commander-luke-skywalker/
![image](https://user-images.githubusercontent.com/33304144/34447969-130d9a76-ec9e-11e7-9eb2-6bc052ce300d.png)
https://swgoh.gg/u/cletus/collection/122/princess-leia/
https://swgoh.gg/u/cletus/collection/235/r2-d2/
https://swgoh.gg/u/cletus/collection/61/barriss-offee/

Zetas for myself and only 1-2 other members are not present in guild view:
https://swgoh.gg/g/18148/empire-kashyyyk/zetas/

Recently synchronized. Not sure if this issue was present before.

**Comment by vitoonto** [comment]
I'm having the same issue. Mods missing and zetas missing

**Comment by danpaulson** [comment]
This should be fixed now. You'll need to manually sync, or wait for your payout to roll around again.
