### ISSUE TITLE
Impossible to login / error 500

### ISSUE THREAD

**Issue by jun-thong** [danpaulson/swgoh.gg.public#120]
Hello,
i'm unable to login in using the form at https://swgoh.gg/accounts/login/.
Thank you for any help.

username : jun21
player id: 953-217-359

**Comment by Locutus1978** [comment]
I have the same problem.
Username: locutus1978

**Comment by danpaulson** [comment]
I just pushed a fix for what I believe was the issue. Let me know if it's still occurring.

**Comment by Locutus1978** [comment]
Now, i can login.

**Comment by jun-thong** [comment]
Working like a charm. 
For my own curiosity what was the problem ? (i'm a dev too...)

**Comment by danpaulson** [comment]
We're working on caching per-guildid, and there is a middleware that sets / unsets cookies related to that functionality. There was an error in the logic that was causing some players to break.
