### ISSUE TITLE
Cannot add my Player ID 

### ISSUE THREAD

**Issue by zombillano** [danpaulson/swgoh.gg.public#122]
Hello there, I tried to add my Player ID on the settings page with no success. Every time I try to add it the page shows a label saying: "Player ID not found. Please ensure you typed it correctly." 

I tried with the Player ID lookup tool with no success, so I guess it is a bug. Can anybody help me?

**Comment by zombillano** [comment]
btw, my aly code is ->888-594-133

I'm not sure about posting my Player ID. My username on swgoh.gg is the same as here

**Comment by PJFry1** [comment]
Same issue, ally code is 749-927-364, user name PJ Fry

**Comment by fr0gg** [comment]
Same issue here as well. I have been trying for the past two weeks and it still doesn't work.
UserName: fr0gg
AllyCode: 366-798-772

**Comment by zombillano** [comment]
please @danpaulson , give us a solution to this problem, it isn't something isolated :(

**Comment by Gwebb27** [comment]
I am having the same problem

**Comment by zombillano** [comment]
@danpaulson
Man, I do not want to sound disrespectful at all, but we are not getting any response from you. At least let us know why this is not working. This thread was opened 17 days ago and it is obvious that you just ignored it.

I know that you are doing this for free, and that any of us have doesn't any right to force you to do something for us, but I hope you can help us.

Here I add both my Player ID and my Ally code:

Ally Code -> 888-594-133
Player ID -> QWiH5HmSvOcZh2QuzLT1A

Thanks in advance!

**Comment by sanktanglia** [comment]
@zombillano your player id is QWiH5HmSvOcZh2QuzLT1A

**Comment by sanktanglia** [comment]
@fr0gg our backend doesnt pull up your player by ally code so i got no clue whats up

**Comment by sanktanglia** [comment]
@PJFry1 your id is fg5BdQTTQUqImbZK6s7m9Q

**Comment by zombillano** [comment]
@sanktanglia that is what I wrote earlier, it still doesn't work :(

**Comment by sanktanglia** [comment]
@zombillano hmm not sure why it didnt paste correctly, add a - before it and it should work

**Comment by zombillano** [comment]
@sanktanglia That finally worked. Thank you so much!! totally appreciated!

**Comment by DDefrost** [comment]
I'm also having trouble with this.  My id is 
diNIpNBR8mdJF1nShMPQa

Can I get some help please?

**Comment by DDefrost** [comment]
My ally code is 991-994-154, sorry forgot that bit.

**Comment by fr0gg** [comment]
@sanktanglia sorry about that, there was a typo on that code. It should be 366-498-772

**Comment by sanktanglia** [comment]
@fr0gg your player id is gGg0SImgTOqFSJFIa67-YQ

**Comment by PJFry1** [comment]
@sanktanglia  that worked, thanks man!!

**Comment by DDefrost** [comment]
@sanktanglia I tried using the player ID tool but nothing happened.  It looked like the page just refreshed.

**Comment by sanktanglia** [comment]
@DDefrost ill get your player id when im home from work, will be a few hours

**Comment by DDefrost** [comment]
@sanktanglia no worries, ty for the reply!

**Comment by sanktanglia** [comment]
@DDefrost your id is -diNlpNBR8mdJF1nShMPQA

**Comment by DDefrost** [comment]
@sanktanglia Thank you! I just had to add - in front with no space and it worked.

**Comment by oddballemt** [comment]
Mine too, please.
681-359-729
VXmugQfKTkaXEzHn7ltLsQ
Crez Yavok

**Comment by sanktanglia** [comment]
hmmm yours looks correct oddball

**Comment by matmills85** [comment]
I'm also having this issue. 
swgoh.gg accepts my ally code 521-591-979 
but doesn't like my Player ID oU00plXZRTWsllRYBGGZWw 
when I submit my details and username Lionhelm into the Player ID Help it just refreshes the page without telling me anything. 
Any help would be appreciated.

**Comment by sanktanglia** [comment]
yours looks correct too @matmills85 well look into it

**Comment by danpaulson** [comment]
@matmills85 @oddballemt can you provide links to your profiles? Thanks.

**Comment by matmills85** [comment]
https://swgoh.gg/u/lionhelm/
User #208883

**Comment by oddballemt** [comment]
sorry. how?

**Comment by oddballemt** [comment]
Whoa. I just got it. the last lower case L was a capital I. WTF?
Thanks for the help.

**Comment by danpaulson** [comment]
![Good News](https://i.imgur.com/REpK0gd.jpg)

The ID Help tool has been updated, and has worked with all test cases in this thread. This should now be far more accurate in providing the PlayerIDs.

https://swgoh.gg/id-help/

**Comment by matmills85** [comment]
Spot on, thanks!

**Comment by ruben19999** [comment]
Disculpen, he intentado un montón se veces registrarme pero no me deja, si alguno me pudiera ayudar estaría muy agradecido. 
Mi código de aliado: 757-111-998
Mi código ID: _Aq2aaWOKOWSrwlxLWp4bA 
Y el enlace de mi perfil os lo dejo aquí https://swgoh.gg/u/ruben1999/

**Comment by ruben19999** [comment]
Me he equivocado en el perfil

**Comment by ruben19999** [comment]
Alguien me puede ayudar por favor

**Comment by danpaulson** [comment]
@ruben19999 https://swgoh.gg/id-help/ - should work for you now.

Closing this thread as the PlayerID lookup tool is pretty accurate now - anything not working anymore is flagrantly wrong.
