### ISSUE TITLE
Sugestion: Structure of Guild API Data

### ISSUE THREAD

**Issue by SdtBarbarossa** [danpaulson/swgoh.gg.public#124]
Hello There!

i had a look at your Guild api data and i feel like they are not well formated.
the sortition on Charakters seems very confusing. Especially because i think the json sets each Charakter to be a own class. This said you could say ok make it a generic class...but then...you dont know wich charakter it is anymore. a good way to compare structures is the firefox webbrowser wich autoformats the data to what it will be later in for example a C# or java class. I would like to suggest you a more comfortable structure.

That said i want you to have a look at my structure:
http://unionderhelden.somee.com/api/gilden

simply open it with firefox or better paste it here:
http://json2csharp.com/

you will find the difference fast. When you paste your data there compared to my your structure will cause lots of classes to pop up. Like said above you could generic this class but then you dont have a charname. Pasting my data to the site will provide you with a very clear strukture. (Where you can ignore "Gildenmember" cause thats used on another stuff ) 

on the simplest its that way:
a "Guild" that holds a List of "MemberListe" objects (actually thats a member) and a MemberListe having a list of "Charakter" objects wich holds the propertys like names and gearlvl and such stuff.

with this strukture you can easyly do several stuff. for example:

- Searching char "Darth Vader" by name:
the "Member" class has a methode findCharByName(string name) wich iterrates through the own list of Chars to find the one wanted.
the "Guild" class has a method findAllCharsByName(string name) wich itterates through Member classes and fire findCharByName of Members. Then you have all chars "Darth Vader" of the actuall Guild.

- finding squads of Chars:
simply itterate through the members calling findCharByName(string name) 5 times and save it in a list.
now you have a Array with an (Array of 5 chars = squad) from where you can pull out all the squads found on the guild.

- sorting chars by Power:
with a comperator you can sort the List of chars each player holds by power.... you can also sort the found list of chars( say all vaders) by power.

those are just some examples. if you need any help with the coding or the structure of datas i would like to help.

please dont see this as disrespect of your work! i really love your side and i appreciate that you guys start an api project. I just want to help you improve this further :-)

Keep up the good work,
greetings sdtbarbarossa

**Comment by danpaulson** [comment]
This API was never intended (or advertised) as an endpoint to be consumed by anyone other than us. We have not released an API intended for consumption by users at this point. If and when we do, it will be well formatted, documented and maintained.
