### ISSUE TITLE
Suggestion: Add release date for characters

### ISSUE THREAD

**Issue by garrettgibbons** [danpaulson/swgoh.gg.public#133]
Hi! Thanks so much for all of your development on this extremely useful resource!

I'd like to toss a suggestion out there: it would be great if each character in the database had their release date added to the general information about that character. It could also be useful to have some sort of page somewhere with a list of each character by release date.

Thanks for your consideration!

**Comment by danpaulson** [comment]
We're working to see if we can get a list of this from CG.
