### ISSUE TITLE
Guild rename needed

### ISSUE THREAD

**Issue by shanara68** [danpaulson/swgoh.gg.public#134]
We have recently joined an alliance and have since renamed the guild. Our original names was White Squadron. Our new name is Ventress White Squadron. We would very much appreciate it if we could get that synced in so that our bots can perform normally. 

Url is https://swgoh.gg/g/1169/whitesquadron/

**Comment by DiegoG619** [comment]
Did they do it for you?

**Comment by shanara68** [comment]
Yes they changed the name in game, but, swgoh still reads the old name

On Jan 16, 2018 9:18 PM, "DiegoG619" <notifications@github.com> wrote:

Did they do it for you?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/danpaulson/swgoh.gg.public/issues/134#issuecomment-358183121>,
or mute the thread

**Comment by DiegoG619** [comment]
So you never received a response from swgoh.gg?

**Comment by shanara68** [comment]
No. Our name still reads White Squadron. We are now Ventress White Squadron.

**Comment by DiegoG619** [comment]
We're you able to change it for us?

**Comment by danpaulson** [comment]
https://github.com/danpaulson/swgoh.gg.public/issues/167
