### ISSUE TITLE
EST Payout timeline wrong

### ISSUE THREAD

**Issue by dnbaxter** [danpaulson/swgoh.gg.public#135]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED

My payout is at 6 p.m. EST, but it's always logging around 7:30 p.m.. The two other guys in my shard chat that we share the same time, theirs is charted at the correct time, but I can't figure out why mine would be wrong. All our settings are the same.

**Comment by dnbaxter** [comment]
https://swgoh.gg/u/dustinb1022/

**Comment by danpaulson** [comment]
It's because EST is the largest payout - around 50,000 accounts now. It takes over an hour to process all of that, so sometimes people get bumped. We are doing what we can to increase sync speed.

**Comment by dnbaxter** [comment]
Awesome, thank you so much for the response and super fast too @danpaulson.
