### ISSUE TITLE
Player ID not found

### ISSUE THREAD

**Issue by Gwebb27** [danpaulson/swgoh.gg.public#136]
Hello,

I have tried multiple times to get my player ID to sync with this site and have been unable to get it to work and it keeps saying my player ID is not found.

https://swgoh.gg/u/settings/

My ally code is  912-111-343
My Player ID is Xgs00Nw3R0-Jgk_TxhQ06Q

Please help me. If there is any additional info please let me know.

**Comment by sanktanglia** [comment]
your player id is XgsO0Nw3R0-JgK_TxhQ06Q
