### ISSUE TITLE
Can you help us change / correct our guild name?

### ISSUE THREAD

**Issue by DiegoG619** [danpaulson/swgoh.gg.public#137]
We have changed the name of our guild with EA. The new name is EchoesOfTheEmpire. Cam you help update it correctly in your awesome site?

https://swgoh.gg/u/diego%20g/

https://swgoh.gg/g/526/mywookiesteakischewie/

**Comment by DiegoG619** [comment]
@scoot1585 can you help us? I don't know who to go to. TY in advance

**Comment by tholbohon** [comment]
Same here.  Changed our guild name over a month ago and thought it would autocorrect and it has not.  New name should be SPC FORCE ASSASSINS for the link to the guild below.  Thanks!
https://swgoh.gg/g/5824/spc-sunrise-park/
