### ISSUE TITLE
Broken 'Select Unit' popup tool

### ISSUE THREAD

**Issue by SirMarcis007** [danpaulson/swgoh.gg.public#138]
https://swgoh.gg/g/2418/persuaders/unit-search/

The feature to search for units within a guild page seems to be broken.  The popup use to immediately return results and allow us to identify unique toons (eg. "General") and before this system error the popup would have displayed results (eg. General Kenobi, General Grievous, etc).  Please fix asap!

--SirMarcis

![persuaders unit search swgoh gg](https://user-images.githubusercontent.com/35541612/35063347-d60b905a-fb94-11e7-909c-ff926dcf2625.png)

**Comment by j0rdanit0** [comment]
Same issue for my guild. This is the URL that's failing: https://swgoh.gg/api/guilds/3087/units/

**Comment by SirMarcis007** [comment]
It's fixed.   Thanks!

**Comment by danpaulson** [comment]
Instance ran out of disk space - thanks for the report.
