### ISSUE TITLE
Wont link to my account in swgoh... 

### ISSUE THREAD

**Issue by Mrzchill** [danpaulson/swgoh.gg.public#141]
I am getting "this player ID doesnt exist" so i use the lookup tool... and retry.... AGAIN nothing. but this time I got an error (pictured below)

my ally code is 293-737-785

ugh im just trying to organize my stuff here! and its not working. help please?
![having issues](https://user-images.githubusercontent.com/35662732/35196224-798fb8a6-fe8c-11e7-8206-afece75dbbee.jpg)

**Comment by sanktanglia** [comment]
what do you think your player id is?

**Comment by Mrzchill** [comment]
fVt0rSMaRTKFSQ8NJye5hw is what the lookup tool gives me

**Comment by Mrzchill** [comment]
which is btw, the exact same one I typed in... lol

**Comment by sanktanglia** [comment]
nah you have an 0 and an o mixed up, your player id is fVtOrSMaRTKFSQ8NJye5hw

**Comment by Mrzchill** [comment]
Thank you Sank... When i put that in is when the forbidden msg comes up as well... :( I copied and pasted yours into it in my settings, and yeah i got the 
Forbidden (403)
CSRF verification failed. Request aborted.

More information is available with DEBUG=True."

**Comment by Mrzchill** [comment]
@sanktanglia any other tips? or am i pretty much hooped lol

**Comment by sanktanglia** [comment]
@Mrzchill maybe try logging in and out? not sure what would cause the csrf to fail

**Comment by Mrzchill** [comment]
log in and out of what? the GG website? or my star wars game? star was was relogged in this week, and i tried even creating a new account on GG with the same results :(

**Comment by Mrzchill** [comment]
omg i got it working! thank you for all your help @sanktanglia
