### ISSUE TITLE
"Description (optional)" link on the squad and squad template creation pages generates error

### ISSUE THREAD

**Issue by interi-mhickman** [danpaulson/swgoh.gg.public#142]
The "Description (optional)" link on the squad and squad template creation pages is broken. Rather than showing/hiding the description field it tries to open the URL "javscript:;" which generates a browser error in both Safari and Firefox.

**Comment by interi-mhickman** [comment]
The problem was staring me in the face. "javascript" in the URL attribute is misspelled. This is an easy fix.

**Comment by danpaulson** [comment]
This is fixed.
