### ISSUE TITLE
Guild Text not updating

### ISSUE THREAD

**Issue by Chakyth** [danpaulson/swgoh.gg.public#148]
Dear Sirs,

unfortunately the guild text is not receiving the updated guild text from the app. Is there a Chance to manually update it? this issue makes it harder to aquire new members, as the TB reward information is old. Please have a look:

https://swgoh.gg/g/757/weltraum-piraten/

Thanks for your help in advance!

**Comment by JothamFett** [comment]
Having the same issue guild greeting not updating nor is the correct amount of members to profiles shown. https://swgoh.gg/g/2939/concorddawn/

**Comment by danpaulson** [comment]
Guild text can only be updated if you are in the top 200 in raid points, as noted here: https://swgoh.gg/g/ We do not have access to guild messages outside of this.

**Comment by Chakyth** [comment]
Hey Paul,
thanks for your Feedback. This was never an issue for us, but now we are focusing on TW.... We have to climb to update! ;-)
