### ISSUE TITLE
Add links to toons on guild zeta page

### ISSUE THREAD

**Issue by offsky** [danpaulson/swgoh.gg.public#15]
On the new guild Zeta listing page, can you please make the pictures of each toon clickable so that we can view that player's stats for that toon?

![screen shot 2017-08-24 at 10 30 49 am](https://user-images.githubusercontent.com/1110926/29679754-57b6a0c8-88b7-11e7-8fdd-778fe2af6969.png)

**Comment by scoot1585** [comment]
this is updated with the latest deploy, thanks for the suggestion
