### ISSUE TITLE
api JSON broken?

### ISSUE THREAD

**Issue by Ch33s3man** [danpaulson/swgoh.gg.public#153]
I'm no longer able to access the guild units api.
when i pass a request to the api for a list of guild units, it starts to return the json but never returns the full JSON data so it won't parse into a proper object.

this does not work for my guild and I found in testing that I have the same partial response regardless of the guild i try to request data for.

if you need further information from me, please reach out.

**Comment by j0rdanit0** [comment]
Same for my guild. https://swgoh.gg/g/3087/theyoungapprentices/unit-search/

**Comment by danpaulson** [comment]
Should be fixed now.
