### ISSUE TITLE
Could you pleaze add this to your website

### ISSUE THREAD

**Issue by phanios** [danpaulson/swgoh.gg.public#154]
While viewing ALL the characters of a player , under each character there is a % of the power of the character. It would be much more helpfull to have the stat power also there since it is missing.
The power of the character does not have the mods in it!!!
Having both the power and the stat power of the character you can know if a character has been changed or not without entering the webpage of the character at all!!!!
I believe this will reduce a lot of the trafic of your website since coders will avoid entering each character webpage to see if something has changed or not since they will have this information at the players webpage!!!!
If all this makes sense to you please add it , If not I apreciate the time and your efforts anyway :)

**Comment by danpaulson** [comment]
Thanks - this should be addressed when we implement a user API.
