### ISSUE TITLE
Add Chars to COI

### ISSUE THREAD

**Issue by Alienater** [danpaulson/swgoh.gg.public#16]
This would be very simple to do programmatically: add all the LS characters to the COI page such as here: https://swgoh.gg/g/15449/team-lnstinct/?stats=coi which will allow guilds to see who is where star/gear wise, and not just CLS and HRS x2. Later when ships get implemented, you can add those too! This is an extremely small fix to something that the SWGOH community will find EXTREMELY useful once TB hits.

**Comment by danpaulson** [comment]
Simple in thought, but certainly not simple in execution. That is an extremely heavy call - 50x ~50 characters. We may expand this section, but the scope of showing everyone is probably not realistically ever going to happen.

**Comment by Alienater** [comment]
would be the financial cost of this call? you could create a vip area with this access ie $5/month with 1 call/day and maybe an excel dump option? maybe some other things in it? Normal users can still use the sight but some can pay for extra stuff

**Comment by danpaulson** [comment]
We tried that previously, only got about 70$ a month. Plus have to build out subscriptions, deal with tax, etc. It's a lot of work at our scale.

But to answer your question, definitely not a financial problem. It would just be an extremely expensive call per guild, and with guild caches refreshing hourly and over 40,000 guilds sync'd, it's an unreasonable amount of calls.

**Comment by Alienater** [comment]
Hmm well then I guess nevermind lol; looking forward to seeing what is in store from you guys nonetheless

**Comment by DilatoryCheetah** [comment]
The biggest use for this would be to coordinate Platoon mission deployment.  You need to be able to see who in the guild has a particular unit so that people don't waste strong units in Platoons and can use them for Special/Combat missions.

**Comment by danpaulson** [comment]
Very good point @DilatoryCheetah - we'll work on getting a feature to support this in the next week or two.

**Comment by DennisBecker** [comment]
I don't know how you store your data but with a database like MongoDB or CouchDB which are good at map/reduce this can be a very fast task.

Have you looked at something like this?

**Comment by danpaulson** [comment]
@DennisBecker We're on MySQL - we've been pining for a move to Elasticsearch for a while, just no time atm to refactor. Hopefully when TB features die down we'll have some time to do so.

**Comment by DennisBecker** [comment]
Seems good. For such complex queries it is hard to fine tune MySQL to be performant. Really interesting that you'll use Elasticsearch in the future but I don't know if Elasticsearch is the right thing as a primary database - but I don't have experience with it besides logstash in a production environment.

**Comment by FingolfinTEK** [comment]
It would be nice to have that functionality out of the box, sure, but since the data is already there people have adapted - some guilds are using scripted Google spreadsheets that pull data from the site and some have created their own discord bots (my guild included) to help with platoon management
