### ISSUE TITLE
[KNOWN ISSUE] Guild Name Updates

### ISSUE THREAD

**Issue by danpaulson** [danpaulson/swgoh.gg.public#167]
Many threads, so creating a master thread.

Guild Names not updating is a known issue, we do not currently have the access to get at this data in a reliable way for most guilds. We are working with CG to remedy this.

**Comment by DiegoG619** [comment]
We are a top 200 guild

**Comment by danpaulson** [comment]
Even with top 200 things appear to be inconsistent. The original way to get this data was basically a hack, and we are working on a way to get something more consistent.

**Comment by DiegoG619** [comment]
Awesome. Thank you

**Comment by TIDUS55** [comment]
Hello guys,
while every personal sync works fine our guild has not been updated in 23 days. Is there any way to force that to sync? It's very important for us, thank you.

https://swgoh.gg/g/35965/starlordsita/

**Comment by danpaulson** [comment]
Closing this - should happen nightly now.
