### ISSUE TITLE
Password Reset Link Not Sending E-mail

### ISSUE THREAD

**Issue by themanicmerk** [danpaulson/swgoh.gg.public#168]
Hi, I appear to be locked out of my account and I've tried every password combination I would usually use. I have tried multiple times to do the reset link but I get no e-mail sent to the account. I have checked spam, trash, all in boxes, etc. I also attempted to create a second account to the same e-mail and got the error that said e-mail already has an account attached verifying that I signed up under the e-mail I had suspected. Please help me, and possibly others who may experience this same problem. I have attempted logging in from multiple devices and attempted the reset link from multiple devices hoping it was device specific. My account is: https://swgoh.gg/u/themanicmerk/ if that helps at all. 

Thanks sincerely,
The Manic Merk

**Comment by mrbeepers** [comment]
Ditto.

**Comment by fbrentwood** [comment]
Myself and at least one other in my guild are having this issue for past two days.

**Comment by 0NLYLAW** [comment]
I've had the same issue! Has any of you been able to recover your accounts?

**Comment by fbrentwood** [comment]
I eventually found mine by trying every password I've used in the past year. The other member of my guild had to create a new account. She was never able to get it fixed.

**Comment by danpaulson** [comment]
You should get an email now - our email service was down.

**Comment by krel73** [comment]
ok so good news is i got the email bad news is after i changed password it
was telling me wrong password when i tried to log in

**Comment by vampyre1973** [comment]
resolved
