### ISSUE TITLE
Zeta report - missing total number, fields mislabeled

### ISSUE THREAD

**Issue by ecdr** [danpaulson/swgoh.gg.public#170]
The labels under the characters on the zeta report say "Total _omegas_", "of all _omegas_"
This should be "Total _zetas_", "of all _zetas_"

Also, there is no number displayed showing how many of each zeta there are.  (The field labeled Total omegas is blank).  This used to display a number of zetas, and on the omega report it still does display a number of omegas.

https://swgoh.gg/zeta-report/

This is on firefox, 56.0.2
also shows that way on Internet Explorer 11

Thanks.

**Comment by danpaulson** [comment]
This is fixed now.
