### ISSUE TITLE
Unable to sync account on SWGOH.gg

### ISSUE THREAD

**Issue by Exile1801** [danpaulson/swgoh.gg.public#172]
Hi,

I’m unable to sync my data with swgoh.gg, when I thick “enable data collection”I get the message “Note that all other SWGOH.GG accounts with this Player ID will be reset. This includes Squads, Arena data, and Unit Sets.” so when I click on update profile nothing happends. Could you help me in rectifying the issue?

**Comment by jaredpoe** [comment]
I am also experiencing this issue. Ever since the 2/27 patch my PlayerID will not sync

**Comment by Pbahn5** [comment]
I am having the same issue. It updates my Arena Rank but characters, ships and mods are not there.

**Comment by pher-ball** [comment]
I am having the same issue. I saw this today both before and after a forced refresh via updating settings. The profile page itself seems to be updated but on the other pages it says that I have 0 characters, 0 ships, 0 mods, etc.
https://swgoh.gg/u/pher-ball/
