### ISSUE TITLE
Sync failure, lost player ID, won't recognize player ID

### ISSUE THREAD

**Issue by Cletus-swgoh** [danpaulson/swgoh.gg.public#175]
I synchronized my account today around 1pm PST. After synchronization I noticed the information was not current. This is common, and typically requires a page refresh. After the refresh the account was still out of date, so I synchronized again. 
Following the 2nd synchronization my account lost its connection to my EA profile and player ID. I have attempted re-entering the player ID (which I am sure is accurate) but it is not recognized.
This is the 2nd time this issue has impacted my account. Other issues have included mod duplication, or mods and abilities not appearing on some characters. These issues do not seem wide spread among users. I wonder what could make my account a higher risk for bugs than other accounts.

https://swgoh.gg/u/cletus/
![image](https://user-images.githubusercontent.com/33304144/36813133-63821850-1c88-11e8-96ff-440d85da8610.png)

Let me know if I can provide any additional information. didn't want to include player ID publicly but can email.

Thanks!
Cletus

**Comment by CaptanHamm** [comment]
Im having this issue as well.

**Comment by sanktanglia** [comment]
its down from the new update, ill fix it up after work

**Comment by CaptanHamm** [comment]
Thanks for the quick response!  and for putting together such a fantastic
utility!  Changed the way i play the game.

**Comment by cArLiLL0S** [comment]
Glad to hear it'll be fixed

**Comment by jpierrard17** [comment]
Awesome mines down too, thanks for the quick response

**Comment by Darth-Amir-IR** [comment]
Same happens to me. How Can I settle it up?

**Comment by jpierrard17** [comment]
@Darth-Amir-IR wait till he fixes it! :)

**Comment by Darth-Amir-IR** [comment]
Awsome! waiting.

**Comment by sanktanglia** [comment]
should be fixed now

**Comment by jpierrard17** [comment]
As always thank you so much for all your work!!

**Comment by Cletus-swgoh** [comment]
Does not appear to be resolved for my account.

**Comment by Cletus-swgoh** [comment]
No wait, there it goes. Just kicked in. Everything looks good.
