### ISSUE TITLE
Missing Stats info on profile page

### ISSUE THREAD

**Issue by bobbir90** [danpaulson/swgoh.gg.public#178]
Hello 
My account does not show me any of my stats on my profile page.
Please fix this. Thanks

https://swgoh.gg/u/bobbir/

**Comment by StankBird** [comment]
I am also experiencing the same issue:

https://swgoh.gg/u/stankbird/

**Comment by Vanadio** [comment]
Same here:

https://swgoh.gg/u/vanadio/

THX

**Comment by Vanadio** [comment]
It is fixed now

**Comment by huwaidee** [comment]
same here

https://swgoh.gg/u/huwaidee/

**Comment by scoot1585** [comment]
The issues with missing characters/mods/ships should be fixed.   We are looking into what is going on with arena history missing.

**Comment by ylixa** [comment]
Same here, yesterday, and today, and every time I’ve tried to use it since joining this useless site since January

**Comment by ylixa** [comment]
HINT:  ITS NOT FIXED

**Comment by sanktanglia** [comment]
@ylixa you didnt even bother to link what page is having trouble and with treating us that way, dont expect a response any time soon
