### ISSUE TITLE
Luminara Role change to Healer not picked up

### ISSUE THREAD

**Issue by MaxTeranous** [danpaulson/swgoh.gg.public#179]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED

Luminara's role changed from Attacker to Healer in the latest update, but she remains as an Attacker on sWGOH.gg.

**Comment by scoot1585** [comment]
this is fixed on the site, thanks for the report
