### ISSUE TITLE
What causes guild information to update?

### ISSUE THREAD

**Issue by johtr** [danpaulson/swgoh.gg.public#18]
I belong to an Alliance and one of our guilds hasn't refreshed for 6 months...is there a way to manually update it?

https://swgoh.gg/g/7071/galactic-warriors-champion/

The Guild name has also changed to Galactic Warriors GotW

Thanks,
John

**Comment by danpaulson** [comment]
Only Guilds in the top 200 are updated currently. We are working on a system to update stats more frequently, but we can currently only get info from the game about the top 200 in terms of guild message etc.

**Comment by johtr** [comment]
Thanks for the quick response, and this is a phenomenal job that you are all doing!
