### ISSUE TITLE
Problems with my swgoh account

### ISSUE THREAD

**Issue by MrScout78** [danpaulson/swgoh.gg.public#181]
Hello
My swogoh account does not show me any information of my stats. No Chars, no Guild Info only an old squad from january 2018. My profile page is disabled.
Please fix this. Thanks

https://swgoh.gg/u/pohli/

**Comment by scoot1585** [comment]
It looks like your sync is disabled, and your ea player id is also removed.  Check your settings, and update those fields, to renable sync
