### ISSUE TITLE
profile was deleted

### ISSUE THREAD

**Issue by huwaidee** [danpaulson/swgoh.gg.public#185]
My profile was deleted and when i logged in it appeared like it was my first day on the site as it only shows my arena rank for 1 day , now it appears like I don't have any mods in my account. 

thanks, 
https://swgoh.gg/u/huwaidee/

**Comment by scoot1585** [comment]
we had some issues with sync, but it looks like your account now has all your characters, mods, and it synced your arena history this morning.  The syncing aspect with missing mods/characters/ships should be fixed.

In re: to your missing arena data, I am looking at the db and there are only two records for your player.  Did you recently try using your ea player id on another swgoh.gg account?
