### ISSUE TITLE
Character, Squads, mods etc. not visible!

### ISSUE THREAD

**Issue by Deantron** [danpaulson/swgoh.gg.public#186]
https://swgoh.gg/u/deantron/

My ships, characters, mods... are not visible anymore! And sync stopped working for a couple of days!

Waht to do?

**Comment by Danimal126** [comment]
Same issue since the update.

https://swgoh.gg/u/danimal126/mods/

**Comment by scoot1585** [comment]
we know what the problem is, we are figuring out a solution, thanks for the report

**Comment by scoot1585** [comment]
This should be fixed, let us know if a manually resync or your next automatic one doesn't fix it.
