### ISSUE TITLE
Guild “Units” page returning incomplete list of members

### ISSUE THREAD

**Issue by j0rdanit0** [danpaulson/swgoh.gg.public#188]
When using the guild “units” feature for TB today, I noticed several of our members were not showing up when they should have been. Here is a URL to our guild’s units page:

https://swgoh.gg/g/3087/theyoungapprentices/unit-search/

**Comment by scoot1585** [comment]
this is related to the problems with sync we are fixing currently, thanks for the report and might be a few hours before its fully fixed

**Comment by scoot1585** [comment]
This should be fixed, let us know if a manually resync or your next automatic one doesn't fix it.

**Comment by j0rdanit0** [comment]
Will do. Thanks so much!

**Comment by garrot7** [comment]
We have same problem. 50 members / 49 profiles. If I search for a character like CLS I get 50 CLS. Why swgoh.gg tells that we have only 49 profiles on swgoh.gg ?
https://swgoh.gg/g/19132/malevolent-marauders/
