### ISSUE TITLE
swgoh gg profile cannot sync even though player id recognised

### ISSUE THREAD

**Issue by Movan8154** [danpaulson/swgoh.gg.public#189]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED

Dear all,

My profile can no longer sync even though player id has been entered correctly. Profile is:

https://swgoh.gg/u/movan8154/

Please can you help?

Thanks!

Movan8154

**Comment by scoot1585** [comment]
This should be fixed, let us know if a manually resync or your next automatic one doesn't fix it.

**Comment by Movan8154** [comment]
Thanks scoot! It's back to normal. Great job!
