### ISSUE TITLE
Corrupted user profile

### ISSUE THREAD

**Issue by DennisBecker** [danpaulson/swgoh.gg.public#19]
We have a guild member "Abandon" twice in our guild. See https://swgoh.gg/g/6884/fireworld/

Abandon is not able to change that and told me that the user profile https://swgoh.gg/u/abandonfw/ could be deleted. He also said he just wanted to change his username in the past and after that it happend that he has 2 user profiles.

Is it possible to delete the user profile https://swgoh.gg/u/abandonfw/ with user ID 23817?

**Comment by danpaulson** [comment]
This is a system-wide issue that we have an in-flight branch to fix. Hopefully out this weekend.

**Comment by johtr** [comment]
I had a player with the same problem of not being able to get his information to show for himself, but his name showed in our guild...so he created a new account. Now he shows 2x in guild. He deleted what he could from the 1st profile, but his name shows up twice still...

https://swgoh.gg/u/deleted/ 

Is the one he tried deleting.

Thanks,
John

**Comment by tdhott** [comment]
Any updates on this issue?  We also have a member of our guild The Laws of Eight that is experiencing an issue where he cannot access his account at all.  He gets the 500 error.  Any page he visits he gets this error.  His user name is jorl/moe.

**Comment by tdhott** [comment]
![img_0248](https://user-images.githubusercontent.com/32652164/31356160-05b2d710-ad0b-11e7-805d-1e344eb01ad8.PNG)

**Comment by tdhott** [comment]
If there was someway to just delete the "/" out of his username I think that would take care of the issue.

**Comment by scoot1585** [comment]
@tdhott Sorry I missed this request. I updated his username to `Jorl_Moe`. (I Think I did this awhile ago when I fixed the remaining user accounts with a `/` in them.  Users can always log in with their email as well.

**Comment by scoot1585** [comment]
I am going to close this ticket as Dan's inflight branch was deployed and I only see one `Abandon` in your guild currently.  if anyone in this thread still has issues, feel free to open a new ticket.

**Comment by DennisBecker** [comment]
Thank you very much for your help!
