### ISSUE TITLE
Email associated with account truncated - locked out

### ISSUE THREAD

**Issue by StephAChamber** [danpaulson/swgoh.gg.public#190]
It looks like I created my account with an improper email - after being logged out and prompted to log back in after a while, I am seeing there is a character-max that forces my email to truncate like this in the sign-in and sign-up 'forms':
stephanieachamberlain@gmail.co 
instead of stephanieachamberlain@gmail.com

I must have missed this when I first created an account--I believe my username is StephAChamber (or stephachamber not sure if caps are considered) and my player id is r_4m9FwpSV2vz_HSmTksSg. I do not have url's because I fail at life and brought this problem on myself. Basically locked out. I really love your product and tools, so I hope you could maybe help me out....

Feeling silly and thank you, 
Steph

**Comment by scoot1585** [comment]
Thanks for using the site and glad you enjoy it!  I took a look and found your account.  I updated the email to be correct and just FYI your current username is `SteCham`

Let me know if you have any other issues getting in.

**Comment by StephAChamber** [comment]
SteCham would make sense that is my player name haha -- thanks so much!
