### ISSUE TITLE
Performance Issue: High CPU use from Chrome (even after loading and during idle)

### ISSUE THREAD

**Issue by Cletus-swgoh** [danpaulson/swgoh.gg.public#191]
Recently my laptop fan kicks on whenever I am visiting. The site has been using 100% of my available CPU, even while idle/background. I also noticed disk and network activity and saw that some ad serving appears to be loading in a kind of loop (these ads also seem new and I hope monetizing works out, its a great site). 

Installing the Chrome extension AdBlockPlus has resolved my CPU issues. I wouldn't use the adblocker if the performance issue wasn't there... but I'll probably just keep it now. Heads up.

**Comment by danpaulson** [comment]
We don't control our ad network, unfortunately. Any bad ads are generally removed very quickly.
