### ISSUE TITLE
Guild message hasn't updated in over a year

### ISSUE THREAD

**Issue by Talon211** [danpaulson/swgoh.gg.public#192]
Hello, Our current message in the game is not syncing with SWGOH.GG. IT's showing a message that was there over a year ago. Need to fix this as the message currently being displayed is the contact info of the previous guild leader.

Thanks
https://swgoh.gg/g/2231/bobba-fetish/

**Comment by danpaulson** [comment]
When a guild is not on the leaderboard, we do not have access to the guild message. Instead of leaving old messages there, we will be removing them from now on.
