### ISSUE TITLE
Swgoh not syncing - Player ID not found

### ISSUE THREAD

**Issue by Jatai77** [danpaulson/swgoh.gg.public#193]
Last week after the new in game update, I have lost all syncing capabilities.  I have tried to resync my account but it keeps saying my Player ID cannot be found.  I know it's correct yet still have not been able to get it loaded.  Any help would be appreciated.

![swgoh](https://user-images.githubusercontent.com/37081984/36990670-d0fe6c0c-207b-11e8-9bbc-79a8ae625803.JPG)

**Comment by Jatai77** [comment]
I got it back working this morning.

**Comment by yodaman98** [comment]
I've had this same issue and as of 5 mintues ago it was still not working for me. What did you do?? I've tried using the player ID tool finder and it doesn't find my ID. This problem has been going on since the update last week.

**Comment by Jatai77** [comment]
Mine was down since last Tuesday.  I didn't do anything different today.  I just tried to resync (as I've done 100 times since then) and today was the lucky day that it synced.  No clue.  Wish I had more info!
