### ISSUE TITLE
password not reseting

### ISSUE THREAD

**Issue by SWTexasJedi** [danpaulson/swgoh.gg.public#194]
unable to login or request password reset for the following account https://swgoh.gg/u/texaspvp/

email should be the same one that is registered for this account. can you send an email request a password update to the email address on file? T_____PVP@gmail.com

**Comment by 0NLYLAW** [comment]
Myself included, please help me recover https://swgoh.gg/u/theonlylaw/ : tevslaw@gmail,con

**Comment by Lazifax** [comment]
Same problem here, could you recover https://swgoh.gg/u/Lazifax/ using the registered mail?

**Comment by MisstySky** [comment]
I have requested a password reset email three separate times and have yet to receive one. Thanks.

**Comment by danpaulson** [comment]
You should get an email now - our email service was down.
