### ISSUE TITLE
Player ID not found

### ISSUE THREAD

**Issue by yodaman98** [danpaulson/swgoh.gg.public#195]
Hey all, I've been having an issue with my accout not showing any of my information since the last update. It's like I never signed up to sync my account to swgoh.gg, everything is blank, even though it was synced before. I've try putting in my player ID to sync and it won't recognize it, I've also tried the player ID tool and it always gives me the same message: "Unfortunately we could not decipher your Player ID. Please check your Ally Code to make sure it is correct, and ensure the Player ID is as close as you can guess." My ally code and in game name are both correct when I type them in. I'd really appreciate the help, thanks!

**Comment by ncusick** [comment]
I'm running into the same issue and I don't see how it can NOT be a bug with the site now.  I have 4 ambiguous characters in my code, 3 of which can be capital i, lowercase L, or one.  The fourth can be either a capital O or zero.  I put together a spreadsheet of 54 possible combinations using those possible scenarios and not one of them works.  There is no other possible outcome of my player ID.  

Furthermore, when I attempt to use the Player ID Help tool using my Ally Code and what I think is my Player ID, the tool breaks and states "It would appear the PlayerID lookup service is down. Please try again later."  One other note, my Ally Code synced without an issue.

Please assist with me getting this synced. Thanks!

**Comment by danpaulson** [comment]
Is this working again? The service was down.

**Comment by yodaman98** [comment]
Nope, it is still not working for me. It's as if my entire accout was deleted, I try inputting my player ID and using the player ID tool and neither work. It's been like this for weeks and my account had been working fine before.

**Comment by danpaulson** [comment]
@yodaman98 could you provide your player ID?

**Comment by yodaman98** [comment]
593-316-585, in-game name is also yodaman98

**Comment by danpaulson** [comment]
And can you provide your PlayerID as well?

**Comment by yodaman98** [comment]
It may be wrong,the capital i's might be lowercare L's or the zeros might be O's but here goes:
Z70nlismQbG-LhurlxfssA

**Comment by danpaulson** [comment]
https://swgoh.gg/id-help/ worked for me with what you submitted.

**Comment by yodaman98** [comment]
Man that's super weird, do you include dashes? Every time I try it always says "Unfortunately we could not decipher your Player ID. Please check your Ally Code to make sure it is correct, and ensure the Player ID is as close as you can guess."

**Comment by ncusick** [comment]
Thanks for the update @danpaulson!!!  I just tried and it finally worked - seems like they got it fixed.  Thanks again!

**Comment by yodaman98** [comment]
@danpaulson Also nothing seems to save on my account, I try to add my ally code or my discord name and when I check back after a couple hours everything is gone again

**Comment by dsharland** [comment]
I'm having the same exact problem. I've used the tool. I've written down all of the combinations it could be because I have 2 zeros or lowercase/uppercase o and 1 capital i or lowercase l. It still doesn't work.

**Comment by hazzard82** [comment]
player id is not working help `? i type my ally code and username in the game correct yet it cand find anything ? and i cant sync my profile because it keeps saying player id not found ?????

**Comment by danpaulson** [comment]
@hazzard82 What is your PlayerID? That is your Ally Code.

**Comment by hazzard82** [comment]
okay that seemed to work thanks

**Comment by yodaman98** [comment]
@danpaulson  Any word on what might be the problem with our accounts? It's been close to a month that I haven't been able to access my swgoh.gg account or be able to check any of my mdos through it. Some help would be incredibly appreciated

**Comment by Krilliks** [comment]
@danpaulson please i have same issue and no response to my post for help, please.

Username: Kilshot
Ally code: 435-568-666
Player ID: G9DS8BtSCGJzO87yH09Qw
