### ISSUE TITLE
Guild name change

### ISSUE THREAD

**Issue by Zone1001** [danpaulson/swgoh.gg.public#198]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED
We recently changed our guild name from Force of Renegades to Zylos Vendetta 4. with the help from EA support.
 How ever, the swgoh,gg guild profile site doesn't update to the new guild name.
 Can you be of assistance?

https://swgoh.gg/g/37321/force-of-renegades/

And just to make sure, our guild name is: Zylos Vendetta 4.

**Comment by danpaulson** [comment]
This should be fixed now.
