### ISSUE TITLE
API

### ISSUE THREAD

**Issue by fheider** [danpaulson/swgoh.gg.public#20]
Is it possible to get an api instead of crawling the html? if swgoh is written in php, i can help if you want!

**Comment by danpaulson** [comment]
That's the plan. https://swgoh.gg/api/ is a very early and sure-to-change example.

**Comment by fheider** [comment]
u need help? i'm a php developer

**Comment by danpaulson** [comment]
We're Django / Python and unfortunately not open source at the moment. But appreciate the offer!

**Comment by DennisBecker** [comment]
Are these the only possible resources for now? GET calls for characters and ships?

**Comment by fheider** [comment]
unfortunately yes

**Comment by danpaulson** [comment]
We are in the process of refactoring our backend, once that is done we will probably be able to expose a lot more for the API.

**Comment by Pikkupomo** [comment]
@danpaulson how is the API progressing? I see you have exposed characters and ships, when do you plan to expose more, like mods?

**Comment by gminorcoles** [comment]
I would like to use this api and would pay for it

**Comment by DennisBecker** [comment]
There are undocumented resources of the API like guild units - are there even more undocumented ones? Like users characters with mods or other resources to fetch detailed data of characters from a user?

**Comment by FingolfinTEK** [comment]
@DennisBecker Great question and one I'd also like to know the answer to - having API access to characters or at least guild's zetas would be fantastic and allow us to create tools to support creating automated team composition tools for various areas of the game.

**Comment by shbi** [comment]
looks like a lot more added.

**Comment by danpaulson** [comment]
Indeed. Still a want of ours to flesh this out, but we're squashing bugs and have a few features to get out ahead of that.
