### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by SANTAJEDI** [danpaulson/swgoh.gg.public#200]
It seems that updating of our entire guild is not happening.  I have asked other guilds and they have the same issue.  Can you please look into this for everyone.  Thankyou.

**Comment by danpaulson** [comment]
What exactly isn’t updating? We do not have access to all guilds info.

**Comment by SANTAJEDI** [comment]
Pretty much everything, we even had a guy join and he's still not listed.
It says it was updated 1 day ago.  We've done manual updates and nothing
changes.  We are missing about 3 mil in gp.  The other guilds I've talk to
have same issue.  I love the site so I'm complaining just wondering if
maybe we did something wrong or idk.

**Comment by danpaulson** [comment]
Nah you didn’t do anything wrong, we just don’t have very good support for guilds from CG - we’re working on it. GP counts require everyone to have joined the site

**Comment by SANTAJEDI** [comment]
Ok thanks,  so the guy who signed up yesterday should show up soon then.
Thankyou again.
