### ISSUE TITLE
account not syncing

### ISSUE THREAD

**Issue by jpurnhag** [danpaulson/swgoh.gg.public#201]
my account is not syncing, even if done manually. update still says 2 days ago when it usually updates nightly.

**Comment by Torton92** [comment]
Hi,
Same issue in my guild.
Moreover, I tried to disable / enable my own account to force sync, and my player id is connecting, as if it was misspelled (but i have a copy paste file, so this is probably a bug from the site).
Anyone with an information about it please?

**Comment by Torton92** [comment]
This is back
