### ISSUE TITLE
Seem to have an issue synchronizing account. Has been 2 days.

### ISSUE THREAD

**Issue by Danimal126** [danpaulson/swgoh.gg.public#202]
https://swgoh.gg/u/danimal126/

Account has not synched in 2 days. Manual synch does not seem to work either.

Thanks in advance.

**Comment by Torton92** [comment]
https://www.youtube.com/watch?v=pAyKJAtDNCw

**Comment by sanktanglia** [comment]
when the servers went down it took down our sync server, should be fixed now

**Comment by Torton92** [comment]
confirmed, thanks, this is back
