### ISSUE TITLE
Guild Info Not Syncing

### ISSUE THREAD

**Issue by schtacky** [danpaulson/swgoh.gg.public#206]
I see multiple issues about the sync server restart and my personal sync works fine. However, our guild has not been updated in 3 days. Is there any way to force that to sync?

https://swgoh.gg/g/615/503rd-legion/

**Comment by mastersavage84** [comment]
I changed my guilds name from savage alliance to the bladeborn but my swgoh.gg account hasn't updated the name or my guilds gp
https://swgoh.gg/g/31995/savage-alliance/

**Comment by Dblade21** [comment]
Same here, guild hasn't updated in 5 days, but lots of changes in status since then.  https://swgoh.gg/g/21439/sent-by-ravens/

**Comment by Volleyrush** [comment]
Looks like I'm not alone.  Five days since our guild info has updated.  Right during TB as well when it is most useful.  https://swgoh.gg/g/4620/west-ren-jdi/

**Comment by Dblade21** [comment]
Ours finally updated

**Comment by danpaulson** [comment]
Check out #167 - We're working on it, have a fix, should be out in the next few days.
