### ISSUE TITLE
Getting forbidden 403 error on trying sync profile ?

### ISSUE THREAD

**Issue by hazzard82** [danpaulson/swgoh.gg.public#207]
Hi, i try update my profile and i get this weird error why? not sure what i do wrong...

Forbidden (403)

CSRF verification failed. Request aborted.

**Comment by danpaulson** [comment]
Check #146 - we're working on it.

**Comment by hazzard82** [comment]
ok now i get different errors, seems it cant find my profile ?

    account_tz
        This field is required.
    ea_player_id
        Player ID not found. Please ensure you typed it correctly.


i have typed it exactly as it appears ingame.. i give up on this :(
