### ISSUE TITLE
New guild name not syncing

### ISSUE THREAD

**Issue by gizmoevans81** [danpaulson/swgoh.gg.public#208]
Hi, we had a guild name change a few days ago and guild page is still showing old name. 
https://swgoh.gg/u/gizmo81/
https://swgoh.gg/g/25966/marks-brothers/

New guild name is '49th Sarlacc Battalion'

Thanks in advance.

**Comment by danpaulson** [comment]
Check out #167 - We're working on it, have a fix, should be out in the next few days.
