### ISSUE TITLE
SWGOH won't let me log in or change my password. It will email me to change password, please help love site but can't use it like intended 

### ISSUE THREAD

**Issue by Hales-minor** [danpaulson/swgoh.gg.public#209]

**Comment by LocCatPowersDog** [comment]
I'm having the same issue. Pretty sure I was using the correct password. Started on mobile login and now my desktop browser has logged me out. Regardless if it's input error on the password the reset password link takes my email but I receive no actual reset password email link. Try to create a new account with the email and of course it says this email/username is already in use.

**Comment by danpaulson** [comment]
You should get an email now - our email service was down.
