### ISSUE TITLE
Omega report - last item - ahsoka tano protective manuever suspicious 

### ISSUE THREAD

**Issue by ecdr** [danpaulson/swgoh.gg.public#21]
In the omega report, the very last item, with only 21 omegas, is Ahsoka Tano's Protective manuever.
Looks like this might be an error.

It is surprising that so few have this omega.  She is a common character.  That is not a bad omega for her, seems much more useful than the omega on her leader ability.  Since she is a pilot, would think some might do her omegas just to boost pilot stats.  My Ahsoka has this omega, hard to believe that only 20 other people would have that omega.

[Edit:] Additional:
This looks even more suspicious since I just found another entry in the listing for Ahsoka Tano's Protective manuever, with 41,000+ omegas.

**Comment by scoot1585** [comment]
hmm this does seem weird.  Ill mark this as a bug and look into it.

**Comment by scoot1585** [comment]
This is updated on live!
