### ISSUE TITLE
Guild pages not updateing to match individual pages

### ISSUE THREAD

**Issue by GeoTank** [danpaulson/swgoh.gg.public#212]
My personal swgoh.gg page shows i have BB8 for example, However when you go to the guild page and do a unit search of the guild it doesn't show me as owning BB8.  This i can see with several guildmates who have aquired new toons in the last few days.  Obviously mostly with new BB8's and Rey (Jedi Training) since their events dropped this week

**Comment by Thailaxy** [comment]
Yes, my guild too. Here on the unit search:
https://swgoh.gg/g/429/thailaxy/unit-search/#REYJEDITRAINING

no new Jedi Rey appear.

even a lot of player unlocked her already
example https://swgoh.gg/u/stl2ega/collection/?f=resistance

**Comment by GeoTank** [comment]
Yes I see similar complaints that are being closed saying it’s the same as the guild name issue. I’m not sure it is but I’m no coder. My personal account shows I just got BB8 

https://swgoh.gg/u/geotank/collection/

But my guild search shows I’m not a member than has him unlocked 

https://swgoh.gg/g/5067/order-88/unit-search/#BB8

**Comment by DylanTusler** [comment]
Same problem here, I've joined a new guild in the last week, and none of my toons are showing when I do a unit search at all even though I show up in the guild member list.
https://swgoh.gg/u/dylan72/collection/

**Comment by CaptanHamm** [comment]
any update on this?

**Comment by FabTimm** [comment]
Same here - no updates to guild unit search results for more than 5 days now. Pretty annoying as we want to monitor the progress in RJTs...

**Comment by GeoTank** [comment]
My Guild has caught up a few times to the individual pages.  Not really caught up it say last update was 6 days ago but i unlocked Wampa 3 days ago and it finally noted that change today though the gear level is off.  So i'd say it's a 3-4 day lag which is not how it used to be and makes planning TB's very hard

**Comment by Dblade21** [comment]
Similar thing happening to our guild. Been 4 days since it updated, not showing all the new Jedi Rey and bb8 that have been earned

**Comment by danpaulson** [comment]
This should be fixed now.
