### ISSUE TITLE
Player name change is inconsistent within SWGOH.GG

### ISSUE THREAD

**Issue by j0rdanit0** [danpaulson/swgoh.gg.public#213]
When a player updates their in-game name, the GG display of that name is inconsistent, depending on where the name is loaded.

Couple of examples:

1. "wooky" (profile) https://swgoh.gg/u/wooky/
vs.
"Wooky" (units search) https://swgoh.gg/g/507/darthmetal/unit-search/#AAYLASECURA

2. "mini" (profile) https://swgoh.gg/u/mini/
vs.
"Mini" (units search) https://swgoh.gg/g/507/darthmetal/unit-search/#ADMIRALACKBAR

Both of these players updated their game name from an uppercase first letter to a lowercase first letter.

**Comment by danpaulson** [comment]
This was a caching issue, which will be updated on a nightly cadence.
