### ISSUE TITLE
Please add filters - Rogue 1, New Hope, Farming location

### ISSUE THREAD

**Issue by ecdr** [danpaulson/swgoh.gg.public#22]
Please add filters to the character lists for:
Rogue 1 - Helpful for territory battles, especially since the app does not seem to expose this tag.
New Hope - Characters needed for Commander Luke event.

It would be very helpful to be able to filter character list by farming location.  
This would particularly help when making farming suggestions.  I could filter somebodie's inventory, and see which characters they have for a location, suggesting other good characters there.  As the game gets more and more characters, it becomes difficult to remember which ones come from where.
e.g.:
Arena Store - (Kannan, Cassian, Mace, Nebbit, Leia, Tarkin, Ugnat, Greedo, Asaj, Savage, HK47, Ackbar, CUP, IG88, Eeth, Sidious, Nute, St. Han)
Cantina Store
Galactic War Store
Ships Store
Guild Store
Territory battles Store
Cantina Nodes
Hard Nodes

**Comment by scoot1585** [comment]
Ah interesting for the store locations.  We will probably add the r1 and new hope filtering sets, but we also have a new concept of character sets we want to roll out that would let people make their own filtering setss
