### ISSUE TITLE
Miscalculated Collection Scores

### ISSUE THREAD

**Issue by strulock** [danpaulson/swgoh.gg.public#221]
Team swgoh.gg,

We have several guild users with misreporting collection scores. See https://swgoh.gg/g/31707/genki-dama/

Note collection scores for:
https://swgoh.gg/u/fredodamaze/  (Shows 4.06, should be closer to 48)
https://swgoh.gg/u/kakarot991/ (Shows 1.25, should be closer to 34)
https://swgoh.gg/u/paullo/  (Shows 1.91, should be closer to 33)
https://swgoh.gg/u/thierry243/ (Shows 1.63, should be closer to 26)
https://swgoh.gg/u/nighthawk9000000/ (Shows 3.16, should be closer to 25)

This started a couple days ago.

Thank you!
Scott

**Comment by pikax** [comment]
I got the same issue, there's other user: https://swgoh.gg/u/gattsu/

Start happening 3 days ago.

**Comment by strulock** [comment]
Looks like the calculation is working now.
