### ISSUE TITLE
Null Values in Characterpower ( Gilden API )

### ISSUE THREAD

**Issue by SdtBarbarossa** [danpaulson/swgoh.gg.public#222]
Somehow some Characters have a Power of 0 even if they have G11 and Lvl 85. 
Please have a look at https://swgoh.gg/api/guilds/39155/units/ and look into the BobaFett of Goga

this happens totally random

**Comment by SdtBarbarossa** [comment]
To clarify: its 0 not null

**Comment by SdtBarbarossa** [comment]
This one seems to be fixed now. Thank xou

**Comment by danielan87** [comment]
This isn't fixed, your page still shows some 0 powers. Same with our guild: https://swgoh.gg/api/guilds/861/units/

**Comment by SdtBarbarossa** [comment]
Ok confirmed the issue still persists. Thx for  clarification

**Comment by danielan87** [comment]
I think this is fixed? Seems to be for my guild

**Comment by SdtBarbarossa** [comment]
Well it could also be randomly not happen. Better we wait for a swgoh.gg dev to response.

**Comment by FingolfinTEK** [comment]
It happened to us a week or two ago and then again a few days ago - it comes and goes at random

**Comment by danpaulson** [comment]
We're doing a lot of work on this side of the project - closing this for now as it seems to be fixed.
