### ISSUE TITLE
Account sync problem(Username error)

### ISSUE THREAD

**Issue by admuyic** [danpaulson/swgoh.gg.public#225]
Dear all,

I can not sync my swgoh.gg account anymore. I am receiving an error as:

“Usernames can only contain letters, numbers, dashes and underscores.”

Thanks for your care.

My account: https://swgoh.gg/u/kyle%20katarn%20the%20imp.%20officer/

**Comment by admuyic** [comment]
?

**Comment by danpaulson** [comment]
You need to update your username to the new standards before syncing. As you state:

“Usernames can only contain letters, numbers, dashes and underscores.”

**Comment by admuyic** [comment]
Do you believe usernames are updateable?
