### ISSUE TITLE
51 profiles in our guild

### ISSUE THREAD

**Issue by OdinOakenshield** [danpaulson/swgoh.gg.public#226]
We have 51 profiles listed in our guild. Grass Toto no longer in our guild and still listing in swgoh.gg

https://swgoh.gg/g/25762/i-club-baby-whales/

https://swgoh.gg/u/grass%20toto/

**Comment by Woweom** [comment]
Hello,I have the same problem.

**Comment by OdinOakenshield** [comment]
Thats the same with our guy, did not move to another guild

**Comment by danpaulson** [comment]
I believe this should be fixed in most cases.
