### ISSUE TITLE
Bug: Ships Stars

### ISSUE THREAD

**Issue by fheider** [danpaulson/swgoh.gg.public#23]
Ships which have 7* only have 90% GP progress. 

e.g.
https://swgoh.gg/u/topperharley/ships/biggs-darklighters-x-wing/
Stars 90% 11,496/12,711 1,215

This should be 100%.

**Comment by scoot1585** [comment]
Stars don't directly give any GP.  They give a multiplier that is used with crew GP to get more power.  So if you read the notes section I put in directly below the ship GP totals, it explains it even further.

It was kinda weird to come up with this, but its the closest thing to chars and I think it makes the most sense when you consider the star GP the total amount you will receive from the highest star multiplier if you had a fully geared ship and crew.

**Comment by scoot1585** [comment]
Updated the display to say "Star Influence", to hopefully get rid of some of the confusion... any way I put it I dont think will sum it up very well with only couple words.
