### ISSUE TITLE
Players not part of guild still showing up on guild page.

### ISSUE THREAD

**Issue by BeansterMaster** [danpaulson/swgoh.gg.public#230]
Two player names are showing up under the guild overview even though they are not part of the guild any more and haven't been for nearly 3-4 weeks.

They are Ish Ren(User#123817) and FryDay(User#81497).

guild page is https://swgoh.gg/g/1239/50shardsofrey/

Could you please address this?

**Comment by danpaulson** [comment]
Good news - this is fixed and will be sorted quickly in the future. Your guild still reads 52 / 50 profiles, there is a script running that should address that soon.
