### ISSUE TITLE
Guild page not refreshed for 23 days and showing wrong PG total

### ISSUE THREAD

**Issue by Borgnasse** [danpaulson/swgoh.gg.public#232]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED

Our guild page is there:
https://swgoh.gg/g/38877/hexagone-plage/

1) It has not been synced for 23 days
2) The logo does not show (broken image)
3) The total PG is the average PG and not the total (assuming the average PG is correct)

It hurts our guild ability to recruit new persons as they do not see our PG. Would it be possible to look after this issue or tell us if something can be done to manually launch a sync for the guild page ?

Thank you very much for taking some time for us !!

**Comment by TIDUS55** [comment]
Looks like we aren't alone. The same things all & all for ours guild.

Our guild page is there: https://swgoh.gg/g/35965/starlordsita/

Thanks very much for all you can do.

**Comment by MoralisRubric** [comment]
Having similar issue with the guild page (https://swgoh.gg/g/12657/ggc-bloodline/) updating, from the time of writing 2018/04/02 19:23 BST, our guild page updated about 15 hours ago, however, the data for the following has not updated:

(1)   Overall GP & Average GP,
(2)   Number of Player states 41 however we have 50 players & all have a swgoh.gg account for over a month or longer,

**Comment by caliclone** [comment]
Same with us: https://swgoh.gg/g/21545/wardens-of-the-old-order-o/
Hasn't updated in, probably, close to a month.

**Comment by danpaulson** [comment]
Thanks all for the report. I believe I've solved the issue on this, and your guilds should be updated now or in the next ~24 hours. The issue was we were ignoring guilds with less than 10 profiles, but never fully checking to see if more profiles had been created. We now do a full scrape every Sunday, and there is a message letting guilds know this if they are below 10 profiles.

**Comment by MoralisRubric** [comment]
My guild page is still not updated and still shows the incorrect information as i reported on this ticket  9 days ago. @danpaulson

**Comment by danpaulson** [comment]
@MoralisRubric I'm going to need more info from you.

What should the GP and Average GP be?

What players are missing? Can you link their swgoh.gg accounts?

**Comment by MoralisRubric** [comment]
@danpaulson The following information for https://swgoh.gg/g/12657/ggc-bloodline/ should be

Total Players: 50
Total Profiles 50
Total GP: 108,534,344	
Average GP: 2,170,687

To my knowledge their are no missing profiles.

**Comment by shocker73** [comment]
@danpaulson 
Same Problem here. Guild was created on 22.04.2018. 
Member: 46
Profiles: 44 Profiles
Not updated since Day 1 or broken are:
Logo
Galactic Power
AVG. Galactic Power
Guild Rank
Raid Points
Arena Rank
