### ISSUE TITLE
Refresh Time

### ISSUE THREAD

**Issue by Snowman418** [danpaulson/swgoh.gg.public#233]
There's no way to adjust the minute refresh time for an account. For example, my payout is 7PM EST. But the update occurs at 7:42PM EST, meaning my stats are not properly recorded. There needs to be a better refresh time adjustment.

**Comment by danpaulson** [comment]
This is because the amount of accounts we have to sync (over 200,000 now). We are working on a system to prioritize higher arena ranks.

**Comment by darthslayer420** [comment]
I give a suggestion  not to get a smart mouth answer  I served my country  to get disrespected with a smart mouth response  next time don't get so but hurt I could have been meaner about it I played nice to get treated like this why? I feel greatly  disrespected have a manager  contact  me you guys know my email address.........

**Comment by darthslayer420** [comment]
Can't even  send a screen shot to you what's going wrong

**Comment by darthslayer420** [comment]
To show you my sync issue

**Comment by danpaulson** [comment]
Upload a screenshot to imgur and post the link? Provide your profile name so we even have a chance of understanding what the issue might be? You've literally given us no information to help you, and haven't clearly explained the issue.

**Comment by darthslayer420** [comment]
DarthSlayer slayerofsouls every time it says synced it. Says my arena rank correct on the top but not the bottom and on top of it my arena team don't update right and shows wrong info

**Comment by darthslayer420** [comment]
The two names are for the same account  it wouldn't  let me change slayerofsouls to DarthSlayer

**Comment by danpaulson** [comment]
https://swgoh.gg/u/slayerofsouls/ - is this it? What do you think the correct rank should be? What is the top and bottom? What info is wrong?

Communication man!

**Comment by darthslayer420** [comment]
Look at my arena a the top it sayarou 2500 but scroll down to current team  it says 3000 and the arena  team I don't have boba  in my current team I switched him out yesterday so when I  got to discord  and do the command /arena it shows the wrong info  and I hit sync like 3 times in one day and no change happens

**Comment by darthslayer420** [comment]
![screenshot_20180410-205254](https://user-images.githubusercontent.com/38148563/38628774-ceef2f6e-3d77-11e8-93ec-278ea37c6176.png)
 
![screenshot_20180411-105544](https://user-images.githubusercontent.com/38148563/38628805-e2830b4a-3d77-11e8-940c-ab627faa2323.png)
![screenshot_20180411-105606](https://user-images.githubusercontent.com/38148563/38628830-f1f2cb6a-3d77-11e8-98ed-61597594e12c.png)

**Comment by danpaulson** [comment]
https://i.imgur.com/xtap1Ww.png - this is the team I see.

The Arena Rank in the profile pane does appear to be wrong, I'll look in to that. Arena ranks only update once a night, at your payout. We do (or should not be) updating when you sync during the day manually.

We have no control of Discord bots nor do we solicit that we do.

**Comment by darthslayer420** [comment]
![screenshot_20180411-110619](https://user-images.githubusercontent.com/38148563/38629050-8c6b3f4c-3d78-11e8-913e-434cbc4a47d0.png)

**Comment by darthslayer420** [comment]
See why I'm not happy now?

**Comment by danpaulson** [comment]
Again we do not support Discord bots in any form. Speak to whoever develops those I guess?
