### ISSUE TITLE
Guild info won't update anymore.

### ISSUE THREAD

**Issue by BobSagetsDealer** [danpaulson/swgoh.gg.public#239]
My guilds overall info hasn't updated in over a month now. New members are still being added or taken away but the overall GP and member average GP won't update. I also think this is causing some issues with our bots on discord.
https://swgoh.gg/g/1601/your-dark-side/

**Comment by djosh79** [comment]
Having the exact same issue. Guild GP and info has not updated in about 2 months. We are 10m GP higher than last update and now a Heroic STR guild. Is there anything we can do to manually sync this? 

https://swgoh.gg/g/2611/legion/

**Comment by VoidACB** [comment]
https://github.com/danpaulson/swgoh.gg.public/issues/267
Lots of guilds having the same issue.

**Comment by BobSagetsDealer** [comment]
Yeah, I've noticed that. Our guild is going on about 4 months now with no update. It keeps adding and removing members but the overall info won't update. Our GP now is almost double what the gg page says it is.

**Comment by scoot1585** [comment]
Closing this as a duplicate, you can follow progress in issue #267 (it should be fixed, just take time to scan all the guilds)

**Comment by BobSagetsDealer** [comment]
Our issue has been fixed now. The image apeears again and info has updated. Thank you. We all greatly appreciate it!
