### ISSUE TITLE
Search ships in "Unit Search"

### ISSUE THREAD

**Issue by DennisBecker** [danpaulson/swgoh.gg.public#24]
I really like the feature to search for a specific character within a guild - now I miss this feature for ships. That would be awesome!

**Comment by DennisBecker** [comment]
My fault - haven't seen in the text that ships will be added soon. Thanks for your great work!

**Comment by scoot1585** [comment]
Yup, this will get added in soon<sup>TM </sup> :)

**Comment by scoot1585** [comment]
This is now live
