### ISSUE TITLE
Last updated timestamp?

### ISSUE THREAD

**Issue by wbtenor** [danpaulson/swgoh.gg.public#242]
On the user's profile page, there is a UTC timestamp when hovering over the tooltip after "Last updated."  

USERNAME'S Characters (135)
Last updated: 22 minutes ago  <------

In the arena graph, the timestamp is in local time when hovering over each payout. This seems to sometimes coincide with the "Last updated" time, and sometimes not, depending on the user. (I am factoring in UTC vs. local time, btw) 

I had thought the arena values were drawn based on the timezone the user chose in their swgoh.gg settings. But, maybe I'm wrong. How do these two values get populated if the user doesn't manually update their profile? Thanks in advance.

**Comment by danpaulson** [comment]
Apologies for the late reply. It's probably off because of the lag between the payout time and when we're able to process. We're in the closing stages of implementing a new system that should address this.
