### ISSUE TITLE
Sith Raid rewards need to be updated

### ISSUE THREAD

**Issue by CaptanHamm** [danpaulson/swgoh.gg.public#248]
Please update the rewards for the Sith raid.

https://swgoh.gg/db/raids/the-sith-triumvirate/rewards/

**Comment by danpaulson** [comment]
https://forums.galaxy-of-heroes.starwars.ea.com/discussion/166824/sith-raid-reward-rollback-4-17-18

Looks like they're not changing :)

**Comment by CaptanHamm** [comment]
what about the guild event tokens?  thats mostly what i was referring to.

**Comment by danpaulson** [comment]
Will wait and see once it's deployed, and we'll update then if it's different. It's all based on game data, so if we updated now it'd just be wrong.

**Comment by CaptanHamm** [comment]
sounds good. Thanks!!!
