### ISSUE TITLE
Guild profile is not updating #712

### ISSUE THREAD

**Issue by hallnote** [danpaulson/swgoh.gg.public#249]
Our guild profile wasn't update since 4 month ago.. what can we do about this?

**Comment by hallnote** [comment]
guild no.712

**Comment by scoot1585** [comment]
Most likely related to issue #267 we will see what we can do about the guild search, but we rely on CG's ingame guild search, which may not work well with certain glyph characters like you are using for your ingame Guild name.

**Comment by scoot1585** [comment]
Closing this as a duplicate, you can follow progress in issue #267 (it should be fixed)
