### ISSUE TITLE
Make guild description refresh

### ISSUE THREAD

**Issue by ivo-cm** [danpaulson/swgoh.gg.public#25]
our guild description is heavily outdated. it also says in the top of the guild page "Last updated 7 months ago".
Please make this refresh regularly like once a week maybe or even once a month would be a great improvement. Or maybe manually with a refresh button.
Our guild page is https://swgoh.gg/g/7626/dutch-delight/ by the way

**Comment by scoot1585** [comment]
we have a branch inflight that will do a lot to update guild stuff.  But the description we currently only get from top 200 guild info.  We think we might have found a way to get more, but will take a little investigating.
