### ISSUE TITLE
CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by BobGod8** [danpaulson/swgoh.gg.public#251]
CSRF verification failed. Request aborted.

Same response to turning on sync and inputting account code.  Cleared cache, cookies, etc, same response.  Chrome, PC, Android.

**Comment by scoot1585** [comment]
Were you able to get past this error?  This sounds like our server was not playing nice at the time you were trying to interact with some form.

**Comment by BobGod8** [comment]
![screenshot_20180515-235037](https://user-images.githubusercontent.com/28109844/40095597-eba5b356-589a-11e8-99ac-9bf79f14d5ae.png)

Nope. Tried a couple times over the last few months, always the same. Code is correct and verified with the checker tool. Just tried now, screenshot attached.

**Comment by BobGod8** [comment]
Worked in the same browser (chrome), on the 4th try, but on a desktop
instead of a phone.

So...it doesn't like the mobile version of the page? *shrugs*  Weird.  A
little less useful for an android mobile app but at least it works now.
