### ISSUE TITLE
Guild roster contains player that left around a month ago.

### ISSUE THREAD

**Issue by SirDavidsonj** [danpaulson/swgoh.gg.public#253]
https://swgoh.gg/g/15998/the-sons-of-dathomir/

Other players added since then are showing but this player has not been removed and roster is showing 50/51

https://swgoh.gg/u/thunderwulf/
Is the player in question.

**Comment by scoot1585** [comment]
Removed the player from your guild.  Thanks for using the site!

**Comment by SirDavidsonj** [comment]
You rock!
