### ISSUE TITLE
Abilities missing from ships' profiles

### ISSUE THREAD

**Issue by geldenhu** [danpaulson/swgoh.gg.public#256]
All ships are suddenly missing details about abilities.
https://swgoh.gg/ships/chimaera/
https://swgoh.gg/ships/biggs-darklighters-x-wing/
etc.

**Comment by scoot1585** [comment]
Thanks for the notification.  This is a common annoyance with some thing we were testing out to import the game data faster and we don't always notice that it doesn't get hooked back up.

Thanks for the notification and this should be showing now.
