### ISSUE TITLE
Guild Galactic Power frozen

### ISSUE THREAD

**Issue by wolfganger11** [danpaulson/swgoh.gg.public#257]
https://swgoh.gg/g/1736/czarne-slonce/

Guild Galactic Power still not correct like a month ago. Avg GP have that same problem.

Could u fix it ?

**Comment by MFlo49** [comment]
Have had same issue with Guild GP frozen for months and the guild message has not updated either. 
https://swgoh.gg/g/230/space-pirates/

**Comment by Timequeen** [comment]
Same here.
https://swgoh.gg/g/2882/german-raid-elite/

**Comment by scoot1585** [comment]
So this seems to be similar to #267.

in @wolfganger11 case the square brackets are throwing off the search, if I remove those I can find you guild again.

in @MFlo49 and @Timequeen cases, our search just can't find your guilds.  We will have to take a look at how we are using the ingame search and see if we can figure out whats going on.  We are at the mercy of CG's ingame guild search for how we find this info unfortunately, but we can see what we can do.

**Comment by VoidACB** [comment]
https://swgoh.gg/g/34211/australian-commandos-b/
I'm having the same issue. Our guild GP hasn't updated in months and the image above it is broken. Our guild description is missing as well. However the member list and their individual GP's are correct.

**Comment by scoot1585** [comment]
Closing this as a duplicate, you can follow progress in issue #267 (it should be fixed, just take time to scan all the guilds)
