### ISSUE TITLE
User is registered, sync enabled, privacy set to public, but not showing properly in our guild

### ISSUE THREAD

**Issue by jasonluc23** [danpaulson/swgoh.gg.public#258]
https://swgoh.gg/u/macebristow/

On our discord channel we run the jedistarbot from crouching rancor, but macebristow does not show up on any reports. Could you please tell me if it's a swgoh.gg or discord issue? It seems like everything is set up properly in swgoh.gg and he's the only guild mate that this is affecting.

Thanks!

**Comment by scoot1585** [comment]
I'm seeing him now in your guild.  I am guessing it was a caching issue.  If there is something else not working, feel free to reply back and let me know.

Thanks for using the site!
