### ISSUE TITLE
Profile stuck in our guild profile

### ISSUE THREAD

**Issue by ztyle-slug** [danpaulson/swgoh.gg.public#261]
In the guild profile
https://swgoh.gg/g/423/intergalactic-space-slugs/
There's a user profile that keeps being there
https://swgoh.gg/u/fire_dragon/
he hasn't been in the guild for over a month now

If you can remove the user profile from our guild profile, I would become a happy slug leader 😄

**Comment by scoot1585** [comment]
There ya go, I took the salt away from ya, so you can be a happy slug :)

Thanks for using the site!
