### ISSUE TITLE
guild search feature

### ISSUE THREAD

**Issue by CaptanHamm** [danpaulson/swgoh.gg.public#263]
Can we get a way to search for registered guilds?

**Comment by scoot1585** [comment]
We hope to bring this out after the new updates we will be bringing out soon.  

See this thread for upcoming changes https://www.reddit.com/r/SWGalaxyOfHeroes/comments/8jhb3m/swgohgg_upcoming_changes/

**Comment by CaptanHamm** [comment]
Thanks much!  I read up on that already! Love it! Looking forward to it.

**Comment by mir0810** [comment]
A Google search is really helpful though ... search on this site only: site:swgoh.gg guildname and you have a great chance ... except all those hyroglyphs ppl put in the names

**Comment by danpaulson** [comment]
We just got access to some endpoints that will make this very doable. No ETA, but will definitely happen.

**Comment by CaptanHamm** [comment]
Awesome!  thanks for the update! go ahead and close out this public issue
if you want, I await the features!
