### ISSUE TITLE
Deleting an account

### ISSUE THREAD

**Issue by 53l3cu5** [danpaulson/swgoh.gg.public#264]
Hi,

Someone in my guild forgot his account so he created another one. 
https://swgoh.gg/g/35004/la-petite-bibliotheque/

Can you delete the out of date account for Locke? (the one with lower gp).
https://swgoh.gg/u/jakuubombassafr/ <--- keep
https://swgoh.gg/u/jakkubombassazzz/ <--- delete

Thanks!

**Comment by scoot1585** [comment]
We don't really delete accounts, and I looked at the account you want deleted and I don't see any sync setup or connected to anything.  Is there any specific reason you need to delete the account?

**Comment by 53l3cu5** [comment]
Hi Scott,
the day after my message the account was out of sync. So today everything
is fine. Thank you very much

Le mer. 16 mai 2018 à 04:30, Scott Benes <notifications@github.com> a
écrit :

**Comment by scoot1585** [comment]
glad to hear and thanks for using the site!
