### ISSUE TITLE
Collection synch very laggy for some users

### ISSUE THREAD

**Issue by DylanTusler** [danpaulson/swgoh.gg.public#269]
We have a player in our guild who is usually #1, but his collection synch happens always more than an hour and a half after his payout time. I can understand a delay, but his is always between 95 and 110 mins after his payout. Has he somehow got set up with a weird synch time?

I've verified his timezone is correct, and we've tried checking/unchecking the collection synch box. Also verified his actual payout time with ea.

Anyway, we'd like to address it if possible, because with his payout time being so far behind of his synch time, he never wants anyone to shift him from #1 until it is through, so the rest of us are patiently watching the site every day waiting for synch.

**Comment by scoot1585** [comment]
Im going to refer you to this post Dan just put out explaining our rewrite https://www.reddit.com/r/SWGalaxyOfHeroes/comments/8jhb3m/swgohgg_upcoming_changes/

The will do two things :

1. Be faster overall (get more people's data much faster)
2. Rank order of sync priority based on what we last synced in your payout time grouping.  

This should help out everyone who is the highest rank to get as close as we can to payout as possible.  We also have seen in our testing that we can scan at much much higher volumes with some other tweaks, so everyone in general should just be faster with this rewrite we hope to get out very soon.

**Comment by DylanTusler** [comment]
Thanks. Removed the link from original post as not needed now.
