### ISSUE TITLE
Quest links to next page not working correctly (Player Activated and Lifetime)

### ISSUE THREAD

**Issue by ultimatox** [danpaulson/swgoh.gg.public#273]
Under Database -> Quests there is a bug if you select either "Player Activated" or "Lifetime" filters, then scroll down to the bottom of the page and click the next page button. Instead of sending you to the next page using that filter, it instead goes to page 2 of "All Quests"

For instance for the "Player activated" page the starting URL is 
[https://swgoh.gg/db/quests/?type=3](https://swgoh.gg/db/quests/?type=3)
the button sends you to [https://swgoh.gg/db/quests/?page=2](https://swgoh.gg/db/quests/?page=2)
instead it should direct to [https://swgoh.gg/db/quests/?type3&page=2](https://swgoh.gg/db/quests/?page=2&type=3)

**Comment by sanktanglia** [comment]
yep we are aware of this one, we rushed this feature a bit :P

**Comment by scoot1585** [comment]
Thanks for reporting this, it is fixed.

Here is also a sneak peak at the new quest styling that will be deployed with the new sync stuff we are working on!

![image](https://user-images.githubusercontent.com/3346556/41016993-6effc2c2-6918-11e8-98d8-1013c07294a7.png)

**Comment by ultimatox** [comment]
Looks great!
