### ISSUE TITLE
Arena sync still broken

### ISSUE THREAD

**Issue by DylanTusler** [danpaulson/swgoh.gg.public#274]
OK I mentioned this last week, and now I'm back.

Since May 24 I've been #1 every day, but it's only been recorded 3 times. Other times it just skips over a day.

Please get your sync working with the new backend soon! I'm finding it very frustrating.

Also, there are a number of others in our shard and in my guild that are having the same problem.
e.g.
https://swgoh.gg/u/dylan72/
https://swgoh.gg/u/brandtlee7/
https://swgoh.gg/u/junao/
https://swgoh.gg/u/pikachoo/
https://swgoh.gg/u/max1muspow3rs/
https://swgoh.gg/u/kuidz/
https://swgoh.gg/u/zorglub/
https://swgoh.gg/u/mugami/
https://swgoh.gg/u/dotard/

**Comment by YankeeDK** [comment]
It's not just arena sync that's broken. Stats are also. My stats say I have 2 gear IX characters, but if you look at my character page, you can count 3. Also 8 vs 10 seven stars: https://swgoh.gg/u/jusu01/

**Comment by DylanTusler** [comment]
Yup still stuck. Only synced 3 times in the last 9 days.

**Comment by jfaldanam** [comment]
You already posted this and already got an answer on #272 , spamming the same issue once and again is not gonna get it fixed earlier, as paul said this should be fixed once they change their backend
