### ISSUE TITLE
Guild Gp not updating, missing image and description #267 #712 #249 #239

### ISSUE THREAD

**Issue by VoidACB** [danpaulson/swgoh.gg.public#278]
https://swgoh.gg/g/34211/australian-commandos-b/
Our guild GP hasn't updated in months and the image above it is broken. Our guild description is missing as well. However the member list and their individual GP's are correct.
![guild gp](https://user-images.githubusercontent.com/39395328/40896671-ae0628e6-67f9-11e8-94ba-636c94434fe2.jpg)

Our guild GP is now a touch over 44m.

**Comment by scoot1585** [comment]
Closing this as a duplicate, you can follow progress in issue #267 (it should be fixed, just take time to scan all the guilds)
