### ISSUE TITLE
Ships API endpoint returns HTML docs instead of JSON data

### ISSUE THREAD

**Issue by FingolfinTEK** [danpaulson/swgoh.gg.public#279]
Hi guys,

I don't know if this is by design but https://swgoh.gg/api/ships/ now returns an HTML API documentation page instead of returning real data like https://swgoh.gg/api/characters/ does and like `/api/ships` did before.

Could you fix this so I don't have to revert to using HTML scrape? :D

Thanks!

**Comment by SdtBarbarossa** [comment]
Maybe its because they trying out some stuff because of my issue here:
https://github.com/danpaulson/swgoh.gg.public/issues/275

I guess giving them a little time is all thats needed ^^

**Comment by SdtBarbarossa** [comment]
Btw you can still force JSON:

https://swgoh.gg/api/ships/?format=json

**Comment by FingolfinTEK** [comment]
Ah, cool, thanks @SdtBarbarossa - I only tried setting the Accept header, never occurred to me to try other ways 👍

**Comment by SdtBarbarossa** [comment]
Yea setting the accept header would be the common way. But that way dont work atm

**Comment by scoot1585** [comment]
What @SdtBarbarossa said was correct.  We use django rest api, which creates documentation from the endpoints, and I ran into some issues where it would lock me into getting the JSON response if I visited the page without specifying the format type.
