### ISSUE TITLE
Certain players showing 0 power for all toons

### ISSUE THREAD

**Issue by Sadumon** [danpaulson/swgoh.gg.public#28]
For example, all of my characters are showing 0 power.  https://swgoh.gg/u/sadumon/collection/

Looks like about half my guild is also showing 0 power for their toons on the guild unit search (GP total seems to be unaffected in the guild roster).

Edit: It seems like it might be related to users who have synced recently (perhaps something broke in your syncing with the BB-8 release or some other change on the CG back-end?)

**Comment by damanar** [comment]
seconded: https://github.com/danpaulson/swgoh.gg.public/issues/28

**Comment by Sadumon** [comment]
Mods also do not appear to be loading.  For example, my CLS is showing no mods but I have him fully kitted out.  

https://swgoh.gg/u/sadumon/collection/commander-luke-skywalker/

**Comment by scoot1585** [comment]
yea we are having some sync server issues.  Basically the summary of it is.  We've been riding the edge of how we had our current sync setup for a little bit.  But the increase number of users and the new ship sync has pushed it over the cliff.  This causes few things to get out of whack.

I have a fix in flight that will increase the amount we can store drastically in our data queue to process  to get us by.  We are working on some more permanent fixes that should allow us back to normal operations.

Each person who has a 0 or missing mods can hit the "Update Profile" button in "Sync and Settings" page which should fix the user up.

**Comment by scoot1585** [comment]
this should be temp fixed with a more permanent solution coming later.  Going to close this.  Please make a new ticket if you continue to see this.
