### ISSUE TITLE
Guild GP and number of members not updating

### ISSUE THREAD

**Issue by oXAllMightXo** [danpaulson/swgoh.gg.public#280]
My guild's total GP is not calculating accurately to reflect the actual total of member GPs with synced profiles. We have 49 members, but the information misreads our total number as 50. It should read as 49 (we have one member who has not sync'd). 

One issue may have to do with the URL. Our guild name is TNR Skywalkers Templar (no apostrophes and that's an "L" not an "i"). 

However, our URL reads "tempiar."

https://swgoh.gg/g/23035/tnr-skywalkers-tempiar/

Is there anything I can do to help resolve this issue? Thanks!

**Comment by scoot1585** [comment]
Closing this as a duplicate, you can follow progress in issue #267 (it should be fixed, just take time to scan all the guilds)
