### ISSUE TITLE
Zeta abilities on character ability page bubble filling

### ISSUE THREAD

**Issue by CaptanHamm** [danpaulson/swgoh.gg.public#281]
Here is a suggestion, for the abilities that a toon has that are zeta abilities, change the final bubble fill color from yellow to purple.

![image](https://user-images.githubusercontent.com/36648742/40993015-ff53b028-68bd-11e8-92b8-ffa8b8c2b994.png)

**Comment by scoot1585** [comment]
I like the way you think :), lucky for you we already have this done in the new sync revamp we are close to releasing.  I also took it a step further and really called out if a zeta or omega is required so it is a little more clear.

![image](https://user-images.githubusercontent.com/3346556/41016677-7bd46144-6916-11e8-8835-36624c1847b9.png)

**Comment by CaptanHamm** [comment]
Awesome!  I was chatting with Dan about it earlier!  He mentioned you had
already gotten to it!  Love it!
