### ISSUE TITLE
Swgoh.gg huild info problem

### ISSUE THREAD

**Issue by TheRealArmo** [danpaulson/swgoh.gg.public#282]
https://swgoh.gg/g/345/fury/ 

None of the header info is right from GP down.....but it shows it updated all the time....truth is we are at 150M now and it hasn't moved in months I know this is a known issue but didn't find a recent answer

**Comment by randocalrissiantheoriginal** [comment]
Yup, we have had the same issue for months..... can we please get it looked into? Thanks!

https://swgoh.gg/g/5946/black-suns-savages/

**Comment by scoot1585** [comment]
Closing this as a duplicate, you can follow progress in issue #267 (it should be fixed, just take time to scan all the guilds)
