### ISSUE TITLE
Meta-Report for Ships

### ISSUE THREAD

**Issue by TobyCooper** [danpaulson/swgoh.gg.public#285]
It would be great if you expend the Meta-Report section with the Arena Ship Battles.

Do you have this data?

https://swgoh.gg/meta-report/

**Comment by danpaulson** [comment]
We have it on our internal to-do list for sure.

**Comment by Vestarakhai** [comment]
Would love to see the meta report on starting ships, reinforcement ships, and most common teams used. Additional what most used ship omegas
