### ISSUE TITLE
Jedi Consular Basic Ability

### ISSUE THREAD

**Issue by TarkTrain** [danpaulson/swgoh.gg.public#286]
The basic ability for the Jedi Consular is listed as "Stabilize", which is a Consular Ship ability.  Consular basic should be "Saber Strike" (which I could not find at all in the Abilities list filtered for Basic).

Same issue with Jyn Erso. (https://swgoh.gg/characters/jyn-erso/)

https://swgoh.gg/characters/jedi-consular/
![swgohgg-consular](https://user-images.githubusercontent.com/40150803/41206227-c5caecb0-6cc6-11e8-9028-bc7a0311fdb7.jpg)

**Comment by scoot1585** [comment]
yea thanks for reporting this, we will be looking into this as a few crew members this got broken... It is really strange because it is not all crew members.

**Comment by scoot1585** [comment]
related: https://www.reddit.com/r/SWGalaxyOfHeroes/comments/8q2yb8/boba_fetts_basic_is_wrong_on_swgohgg/

**Comment by scoot1585** [comment]
This is fixed, thanks again for letting us know

**Comment by TarkTrain** [comment]
Awesome, thanks for the quick fix.  Really appreciate the site.
