### ISSUE TITLE
Low Cadence Guild Not Updated

### ISSUE THREAD

**Issue by dbrowdy** [danpaulson/swgoh.gg.public#287]
### LOOK THROUGH EXISTING TICKETS TO ENSURE YOUR ISSUE HAS NOT ALREADY BEEN CREATED
![image](https://user-images.githubusercontent.com/40177490/41244164-11fe71e6-6d59-11e8-9287-d891dfe373b3.png)

https://swgoh.gg/g/44683/ungenii-shaddaa/

This guild hasn't refreshed yet and we are no longer "low cadence" so it would be nice to get back onto a normal cadence.  Thanks!

**Comment by scoot1585** [comment]
just resynced the guild and you should be good to go

**Comment by dbrowdy** [comment]
Awesome, thx!
