### ISSUE TITLE
Guild Members Not Updating

### ISSUE THREAD

**Issue by kickinbahk** [danpaulson/swgoh.gg.public#29]
My Guild shows as having not updated in 23 days. I am not 100% sure about the timeline, but I do know that it hasn't updated recently, since it is showing some members that are no longer in our guild. Is there a way to force it to check the current guild members and data? 

guild url: https://swgoh.gg/g/27992/teamskunk-republic/

**Comment by danpaulson** [comment]
This should be fixed in the next day or two.
