### ISSUE TITLE
Guild is not updated

### ISSUE THREAD

**Issue by shocker73** [danpaulson/swgoh.gg.public#291]
Our Guild was not updated for 2 month. Page is: https://swgoh.gg/g/41450/443rd-bataillon/

It has not been synced since the first day.
The logo does not show (broken image)
The data for Galactic Power, AVG. Galactic Power, Guild Rank, Raid Points, Arena Rank are not shown.

Thank you in advantage for your help.

**Comment by achoukah** [comment]
We merged guilds over a month ago, and it states as of the time of writing ‘updated 12 days ago’ and that ‘This guild has less than 10 profiles, and thus has a lower cadence to update. It will update every Sunday evening.’

Page: https://swgoh.gg/g/44663/knights-of-mandalore/

![ea2a92f0-8d7b-4206-a1ce-ba55e52c6472](https://user-images.githubusercontent.com/507069/41627266-804595e8-7417-11e8-8c67-e3d64fd7bd3f.png)

**Comment by AdmiralP** [comment]
Similar issue - guild has not synced for 21 days. Has EA closed some door preventing this from working as it once did? Or are the smaller guilds just no longer being synced?

https://swgoh.gg/g/18742/shifting-veers/

**Comment by eris3d** [comment]
I have same issue with https://swgoh.gg/g/20646/feeltheforcero/
Updated 22 days ago and says "This guild has less than 10 profiles, and thus has a lower cadence to update. It will update every Sunday evening." but Sunday evening just passed and it didn't update aaaand we do have more than 10 profiles, so it shouldn't say this.

**Comment by danpaulson** [comment]
You all are now updated, but we are still investigating why our other sync is not working. Thanks for your patience.
