### ISSUE TITLE
Meta report: number of teams do not add up

### ISSUE THREAD

**Issue by Rockseia12** [danpaulson/swgoh.gg.public#294]
The meta report for the number teams is supposed to be comprised from 4161 teams ( as of June 20), yet when you add up the rank 1 leaders, it adds up to 8570. Is there an issue with the way you count teams?

**Comment by TobyCooper** [comment]
i guess there is a general Problem with the meta Report. By the Leader and all Characters are the numbers way to low and there is also no % calculation

**Comment by TobyCooper** [comment]
Helllo?

**Comment by sanktanglia** [comment]
we are currently working on reworking alot of our backend processing including the stuff behind the meta report, its coming soon so most likely any fixes will come along with it

**Comment by TobyCooper** [comment]
@sanktanglia Thank you for the Feedback. 
If you do not know the percentages calculation isn't correct. summed up with all character, there are far more than 100%

hope this helps

**Comment by danpaulson** [comment]
This will be fixed with the new version of the backend; we don't intend on fixing the current version.
