### ISSUE TITLE
swgoh.gg account is not longer synching.

### ISSUE THREAD

**Issue by mjaycocks** [danpaulson/swgoh.gg.public#295]
My swgoh.gg profile (https://swgoh.gg/u/mjaycocks/) hasn't synched for the last couple of days. Checked others within the guild and it is the same their profiles were last synched two days ago. I suspect the synch service has stopped.

Thanks
Mark

**Comment by mjaycocks** [comment]
If I do "Settings and Sync", "Update Profile" it then shows:
![image](https://user-images.githubusercontent.com/33319414/41721502-f3f55144-755d-11e8-95cc-4ece6fbb9879.png)

**Comment by hansenwebco** [comment]
Having the same issue on my profile. https://swgoh.gg/u/stonedonkey/

**Comment by raddad67** [comment]
I have had the same issue. I've been watching my Arena rank and it's not updating. https://swgoh.gg/u/raddad67/

**Comment by mjaycocks** [comment]
This issue is now resolved for me.
