### ISSUE TITLE
Arena rank not updated 

### ISSUE THREAD

**Issue by felipedmori** [danpaulson/swgoh.gg.public#300]
My arena rank is not updated, last time was a month ago. everything else is synchronizing correctly.
I found some other topics with this but no one with a solution that I can do.

my account link.
https://swgoh.gg/u/felipedmori/

User #53805

**Comment by raddad67** [comment]
I am thinking that the Syncing issue that was fixed is different from the Arena ranking. That's what I keep looking at because I've made top 20 a few times and it's still showing my old team.

https://swgoh.gg/u/raddad67/

Thank you in advance.

**Comment by ITMicaH** [comment]
Same problem here. Arena rank stopped syncing after june 19th:

https://swgoh.gg/u/kashyyykwarrior/

**Comment by CoMiGa** [comment]
I checked the top 5 or so people in my guild and none have an arena rank newer than the 21st.
https://swgoh.gg/g/3711/council-of-jeth/
Mine was last updated on the 20th 
https://swgoh.gg/u/comiga/

**Comment by ITMicaH** [comment]
I see sync is fixed for most players. Mine is still broken. 

https://swgoh.gg/u/kashyyykwarrior/

**Comment by felipedmori** [comment]
![image](https://user-images.githubusercontent.com/20077029/42097177-d5645064-7b8d-11e8-8b83-323a97945226.png)

![image](https://user-images.githubusercontent.com/20077029/42097210-ea3cba76-7b8d-11e8-893d-b58c4a2befd9.png)


The problem is not on the chart synch. 

The rank on attached images is the problem, even the average rank looks to be ok. but arena rank still showing 38, analysing the chart I'm not be 38 any day on current month

**Comment by ITMicaH** [comment]
Strange. Mine says: 

Arena Rank - None (I joined june 7th)

The chart shows no sync after june 19th which sucks cause I'm on #228 right now while at that time I was on #706.

**Comment by danpaulson** [comment]
The profile pages are fixed. Guild pages will be fixed when we roll out the new backend.
