### ISSUE TITLE
SYNC STILL NOT WORKING MONTH 4

### ISSUE THREAD

**Issue by Krilliks** [danpaulson/swgoh.gg.public#303]
Please sync my account or fix this issue it's been months now, and no response to any ticket! I used your look up tool still does not work sends error back. Guilds require this also I have 2 different user #s when you look it up, which may be cause, please investigate and correct. Thanks.

Bigkils
Https://swgoh.gg/u/Bigkils
User #246480 or #224179 

Username: Kilshot
Ally code: 435-568-666
Player ID: G9DS8BtSCGJzO87yH09Qw

**Comment by AdmiralP** [comment]
You are missing part of your ally code. This includes the hyphen that precedes it. Copy and paste the next line exactly as it appears and you should be good. 

-G9DS8BtSCGJzO87yH09Qw

I'd imagine the hyphen looked more like it was a delimiter than part of your ally code, but it is part of it. The codes are 22 characters in length. 

Hope this helps.

**Comment by danpaulson** [comment]
Thanks @AdmiralP - definitely correct. That said, it appears your account is syncing?

**Comment by Krilliks** [comment]
Yes a friend helped me out the  A-day so I can join a new Guild thanks
