### ISSUE TITLE
Guild not updating - 4 days

### ISSUE THREAD

**Issue by celsogbj** [danpaulson/swgoh.gg.public#304]
My guild was not updated for 4 days, Could you please give it a look? 

our address is: http://swgoh.gg/g/2430/team-treta

Best regards,
Celso

**Comment by danpaulson** [comment]
Hmm. Has this guild been disbanded?

**Comment by Appleidroids** [comment]
I join, we also do not update the information on the arena of players since 19.06.18 https://swgoh.gg/g/28720/4pda-kamino-dark-side/ & https://swgoh.gg/g/686/4pda-kashyyyk/
