### ISSUE TITLE
Guild not updating - 25 days

### ISSUE THREAD

**Issue by AdmiralP** [danpaulson/swgoh.gg.public#305]
https://swgoh.gg/g/18742/shifting-veers/

Up until recently our guild did not have enough members to refresh more than the once weekly, Sunday sync. However, it has been 1 month+ since our last update. 

We have actually increased our presence here significantly in the last week. So we are looking forward to getting more frequent updates. 

Thanks for the work you have put into the site. It has been a real great asset to me while improving my inventory in-game. Looking forward to the guild getting that same benefit. 

Please let me know if you need any additional information. 
![shiftingveersnosync](https://user-images.githubusercontent.com/33196541/42064079-700f9ef0-7afa-11e8-9294-1538f3c21245.png)

You may or may not have noticed that I had this same issue posted previously, closed it, and then immediately reopened it. My apologies. That was a misunderstanding on my part, and we would still like to see about getting the guild synced.

**Comment by cadetill** [comment]
Hi mates

Another 2 guilds not updated 

https://swgoh.gg/g/42896/la-alianza-contraataca/
https://swgoh.gg/g/46156/el-retorno-de-la-alianza/

Thanks for your great work :-)

**Comment by Shamix808** [comment]
Also not updating;  currently at 48/50  with 100+m

https://swgoh.gg/g/45041/shadowlands/

**Comment by danpaulson** [comment]
You all are now sync'd. I'm not 100% sure why the Sunday sync isn't working, but manual execution worked.
