### ISSUE TITLE
Arena Rank in Profile Box not updating

### ISSUE THREAD

**Issue by IndyStarfarer** [danpaulson/swgoh.gg.public#308]
Good day,

Over the past few months I have noticed that the Arena Rank in the profile box on the left of the window has not been updating, whereas the Current Rank number does (however irregularly). Mine has read "Arena Rank 826" since April, but my 'Current Rank' reads 503 at the moment. 

![swgoh profile page](https://user-images.githubusercontent.com/38267916/42222787-27ef483e-7ea4-11e8-8644-c0ef2fbe2d32.png)

Thanks,
Mk

**Comment by danpaulson** [comment]
This has been fixed.

**Comment by IndyStarfarer** [comment]
Thanks, Dan!

Mk
