### ISSUE TITLE
Shard Shipments - Guild Events Store

### ISSUE THREAD

**Issue by zizoun-github** [danpaulson/swgoh.gg.public#31]
Hello, could you guys add Guild Events Store to Shard Shipments? Thanks.

**Comment by scoot1585** [comment]
We need a "reliable" source of what is all contained in that before I start manually mapping them.  Since those aren't static lists we have to add them manually to a list that is ran when we do our data import.

If you can point me to a source that lists everything, I can add that in.

**Comment by zizoun-github** [comment]
I can't vouch for this but it's the most complete list I've found so far:
https://forums.galaxy-of-heroes.starwars.ea.com/discussion/130036/list-of-content-in-the-guild-event-store

**Comment by scoot1585** [comment]
Nice, thanks for finding that.  After looking at this and checking it out past few days I would say this "looks" correct.  I'll prob go with the implement it and ask for forgiveness if anyone finds an inconsistency heh :)

**Comment by scoot1585** [comment]
Character shards have been added.  Once I add some styles for how ship shards look, I will eventually add ship shards to the different shops.
