### ISSUE TITLE
Error 500 acessing user profile

### ISSUE THREAD

**Issue by celsogbj** [danpaulson/swgoh.gg.public#311]
I am getting error 500 when I try to access the profile of one of my guild mates throught the list of members on my guild profile.

User profile(this link gives error 500): https://swgoh.gg/u/caca86/

Guild profile: https://swgoh.gg/g/2430/team-treta/

Can you please give it a look?

Best regards,
Celso

**Comment by eris3d** [comment]
https://swgoh.gg/u/ijjasz/ gets the same, probably it's not just an isolated case, although I see yours (caca86) it's ok now...

**Comment by danpaulson** [comment]
Just pushed a fix, looks to be fixed!
