### ISSUE TITLE
Account Won't fully Sync (Only Ships)

### ISSUE THREAD

**Issue by IBYoda** [danpaulson/swgoh.gg.public#312]
Account: OutlawV
Ally Code: 933783428
Player ID: 5sjBBBeXRda01falJfu0vA

I have had the account for a long time and the Character Sync Has never worked. On the initial set up I always get a 500 internal Server Error when trying to set up the Sync. It takes the information but when hitting update Profile on https://swgoh.gg/u/settings/ and flips to https://swgoh.gg/u/outlawv/ , I immediately get the server error. However the Settings DO TAKE and it does sync the SHIPS only but nothing else. 

https://swgoh.gg/                               Works
https://swgoh.gg/u/settings/              Works
https://swgoh.gg/u/outlawv/ships/     Works

https://swgoh.gg/u/outlawv/                       500 Server Error
https://swgoh.gg/u/outlawv/mods              500 Server Error
https://swgoh.gg/u/outlawv/squads            500 Server Error
https://swgoh.gg/u/outlawv/collection        500 Server Error

**Comment by danpaulson** [comment]
Pushed a fix!
