### ISSUE TITLE
Account won't fully sync

### ISSUE THREAD

**Issue by Rand1969** [danpaulson/swgoh.gg.public#313]
Account: Rand1969
Ally Code: 958956578
Player ID: lc99McxDTUOOCGfDQGg6Gw

My account is syncing ships and is reading my gear info but hasn't brought over anything with characters or mods.  

Can you please see if I did something wrong.

https://swgoh.gg/u/rand1969/
https://swgoh.gg/u/rand1969/collection/

**Comment by danpaulson** [comment]
Just pushed a fix, let me know if that resolves the issue.
