### ISSUE TITLE
Account won't sync

### ISSUE THREAD

**Issue by Dr4gonR4ge772** [danpaulson/swgoh.gg.public#315]
Account: Dr4gonR4ge772
Ally Code: 788-363-248
Player ID: 341705418806001665

500: Internal Server Error
Its not my fault!
It probably is

**Comment by danpaulson** [comment]
Just pushed a fix, let me know if that resolves the issue.

**Comment by Dr4gonR4ge772** [comment]
It did resolve it. Thank you very much!
