### ISSUE TITLE
Payout Time

### ISSUE THREAD

**Issue by Snowman418** [danpaulson/swgoh.gg.public#318]
The script that scraped my arena rank is consistently 44 minutes late which obviously makes the reported rank stale.

What's the deal with this. I rank number one or two it's not like my account is some garbage 200+ arena rank. The system should prioritize high ranking accounts.

**Comment by danpaulson** [comment]
This drift exists because of the sheer amount of accounts we have to sync. We're rolling out a new system soon that will sync by previous rank, so higher ranks will be prioritized, along with the sync being much faster.
