### ISSUE TITLE
Guild / Collection /  No G12 Column Displayed

### ISSUE THREAD

**Issue by RoughingTheSnapper** [danpaulson/swgoh.gg.public#33]
Hello! Thanks for the awesome tool. I would really apprciate it if you might be able update the table on the Guild/Collection level to include a column for G12. I rely on the table to track gear progression at the guild level for HAAT suitability, and guys with G12 look weaker than they should. Thanks for your consideration.

**Comment by scoot1585** [comment]
Should be easy to add since we are recording that, we just need to add it to the display.

**Comment by RoughingTheSnapper** [comment]
Awesome!! Thanks!

**Comment by scoot1585** [comment]
Updated the template to show it.  May take a bit to clear the caches but you'll see it soon.

**Comment by RoughingTheSnapper** [comment]
It's showing up. Thanks again!
