### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by Spenc84** [danpaulson/swgoh.gg.public#35]
**On the following page:** https://swgoh.gg/sync/
**Under the following section:** Frequently Asked Questions
**Under the following subsection**: My Player ID doesn't work!
**In the following sentence:**  A lot of characters (_**Capial**_ O vs Zero, lowercase L vs Capital I) look very, very similar.

_Capial_ should be changed to _Capital_

**Comment by scoot1585** [comment]
Good eye heh.  Fixed this.
