### ISSUE TITLE
Add a character filter for 'Tenacity Down'

### ISSUE THREAD

**Issue by Spenc84** [danpaulson/swgoh.gg.public#36]
Presently you can filter characters by 'Tenacity', which will show you a list of all characters who can apply 'Tenacity Up' or 'Tenacity Down'. However, since there are so few characters who can actually apply 'Tenacity Down', and since it's a fairly important debuff for raiding, it would be nice to have a list of just those characters.

**Comment by scoot1585** [comment]
Good suggestion.  I split Tenacity to Tenacity Up/Down and I also added Daze, since it is so useful in TB and people may be curious who all has it.
