### ISSUE TITLE
Buggy guild member

### ISSUE THREAD

**Issue by FabTimm** [danpaulson/swgoh.gg.public#37]
Hello,

I'm from the guild Hexagone Kappa. We have since some weeks a name (axeloums) - https://swgoh.gg/u/axeloums/ listed as guild member but he's not at all part of our guild.
Is it possible to delete this line from our guild roster ?
Thanks in advance.

**Comment by CaizSW** [comment]
Our guild also has a "corrupted" roster member.  https://swgoh.gg/g/1299/mighty-chiorians/  lists Freak of nature (https://swgoh.gg/u/freakofnature/) as a guild member but he\she is not.  Can this be removed on the DB side of things?

**Comment by scoot1585** [comment]
I fixed both of these.  Hopefully we can have a fix for a couple more edge cases where this happens soon.

**Comment by SirDavidsonj** [comment]
Having a similar issue with Guild Member CostaHD2 in https://swgoh.gg/g/15998/the-sons-of-dathomir/  Costa has not been a member for a few months at least.
