### ISSUE TITLE
Love the Website!  Guild Msg Update (within top 200)

### ISSUE THREAD

**Issue by Iwan55555** [danpaulson/swgoh.gg.public#43]
Guild has been in the Top 200 constantly either Rancor or Haat Leaderboard, and everything gets updated
perfectly except the Guild Message,

And as we put in our Website, and application Form we really like to see it updated.

Has been done more then a week ago. and still shows the old Ingame Guild Text

**Comment by scoot1585** [comment]
We can only sync what we see.  If you fall out of top 200 when we sync (this is the important part), we can't see messages.  We might have a way to get this we are looking into, but for right now, not much we can do.

**Comment by Iwan55555** [comment]
Yes i understand that. but have been within top 200 every day.  
We are also top 10 arena average ranked so that why we also stay in top 200 for rancor/haat

**Comment by scoot1585** [comment]
hmmm, what is your guild link?

**Comment by Iwan55555** [comment]
https://swgoh.gg/g/84/team-steroid/

Sad its out of the top200 since today somewhere.. but the message is changed 10days ago. and last week of the month have been entirly been in top 200

**Comment by scoot1585** [comment]
ah, so I think I found the issue.  I'll need to talk through this with dan as this was caused by other updates we've done for calculating guild info.

**Comment by scoot1585** [comment]
This is fixed.  Found the actual problem and let's just say we were basically only syncing the top 10 from each leadboard heh.
