### ISSUE TITLE
Players No Longer Syncing in SWGOH.gg

### ISSUE THREAD

**Issue by shodge12** [danpaulson/swgoh.gg.public#434]
I keep stats for my guild and use SWGOH.gg.  I have two players which previously worked but for some reason they are no longer syncing.  The data stored is only.  Can you correct?  I apologize if this is the incorrect forum for this...

Players:
https://swgoh.gg/p/265918851/
[This player can sync when re-logging in but no auto checkbox is visible]
https://swgoh.gg/p/681887327/

THanks,
..Stan

**Comment by sanktanglia** [comment]
also wow i feel so stupid, we missed including the auto sync button on this page. I went ahead and flagged all of your accounts to auto sync and i am readding the option on the sync form, thx for the report!

**Comment by Nuitarius** [comment]
My account has not updated for 10 days now. Thought waiting would fix it, but I guess writing in this forum is the only way?? Under Settings it says sync status is "Active".
https://swgoh.gg/p/642984934/

**Comment by shodge12** [comment]
You can close this now.  The original members are now sync'ing and fixing the collection sync checkbox will address it in the future....
Thanks,
.Stan
