### ISSUE TITLE
Guildmember's inconsistent ordering by name.

### ISSUE THREAD

**Issue by baldusi** [danpaulson/swgoh.gg.public#46]
When the guild members are ordered by alphabetical order, you use their swgoh.gg account name. This is inconsistent since you actually display their in-game names. Could you order by in-game name? People with alts or popular names have resorted to very obscure and generally completely different account names. I know also, that you are going to eliminate account names. But ordering by email would also give the same inconsistency (and add information leak).

Regards

**Comment by scoot1585** [comment]
This is updated to sort by player name on live now.
