### ISSUE TITLE
Recording time of Arena Rankings

### ISSUE THREAD

**Issue by Iwan55555** [danpaulson/swgoh.gg.public#48]
in my guild i have a couple of guys who every day get their arena rank recorded at a later moment , example https://swgoh.gg/u/pm89/
![naamloos](https://user-images.githubusercontent.com/32458020/31152307-c4099d58-a89b-11e7-88bf-2ea3c9edc01b.png)

he has them evertime 40 minutes after his actual Payout Time..   We tried alrdy choising other timezones(different cities but matching timezones) but nothing fixes it..

We same as other guilds try to get on top of the rankings.. But this aint helping us.

As I am also pushing Guildies up to get rankings up. but if swgoh.gg doesnt show in some cases of players not the actual rank but 20-40-45 minutes after their actual PayOut it wouldnt be fair.

Please help me out..

**Comment by scoot1585** [comment]
Sorry but there is not much we can do for you.  I am going to quote from my original post on reddit when I explained how the sync works when I first implemented it.

source: https://www.reddit.com/r/SWGalaxyOfHeroes/comments/50dvnn/swgohgg_new_features/

> You can now set an "Account Timezone". This will allow you to configure when the arena sync feature and your own profile sync runs daily. Whatever timezone you choose, at 6pm in that timezone (NOT including DST), it will run your character sync with everyone else in the same timezone. This means that if there are 1000 people with EST timezone set, it will queue everyone up at the same time and your specific sync may not run exactly at the hour mark. We are working on improving the sync speed so we can get this closer and closer.
> * ex: Your Account Timezone is "(GMT-06:00) US/Central"... the automatic sync for you will run at UTC 00:00
> * If you DO NOT set a timezone it will default to midnight EST or 5am UTC to begin the sync. Note that it will be a long queue (lots of accounts)
> * You can still force a sync of your collection by clicking the "Update Profile" Button on your settings page, but the arena sync will only run in the automatic sync mode
> * You can only change your account timezone once in 24 hours

We have limited resources and no official API, so we continue to try to improve it, but currently there is nothing more we can do to change when your specific accounts sync at, that wouldn't be fair to everyone else in the same timezone as you.
