### ISSUE TITLE
New Guild Members Not Showing Up

### ISSUE THREAD

**Issue by Cypher82** [danpaulson/swgoh.gg.public#49]
Hi,

Hate to bother you guys with anything, because you do so much for the community.  But new guild members aren't showing up on our list.   I'm guessing the issue is that we had CG change our guild name and thats causing issues.  Was wondering if there was a way to fix this.

https://swgoh.gg/g/10045/nolightnodarkonlyforce/

Thanks in advance!

Cypher

**Comment by Cypher82** [comment]
Now getting 

404: Not Found - This isn't the page you're looking for. Messages as well.

**Comment by scoot1585** [comment]
Uhhhh, can you give me an example of a swgoh.gg account that should be associated with your guild and isn't?  I'll have to look into what the data is telling us.

And in re: to the 404, how do you get to the 404 page?  what link is taking you there?

**Comment by scoot1585** [comment]
This should be fixed with #52 by the sounds of it.  Closing for now til more info that says otherwise
