### ISSUE TITLE
Guild Member Missing from Guild Profile

### ISSUE THREAD

**Issue by SnakesOnAPlane** [danpaulson/swgoh.gg.public#5]
Everything appears normal here:

https://swgoh.gg/u/ferrrozizard/

But he doesn't list here:

https://swgoh.gg/g/5057/north-american-refugees/

Thanks!

**Comment by scoot1585** [comment]
Hey there,

That profile needs to turn their profile privacy to "public" in settings in order for it to appear on the guild listing

**Comment by SnakesOnAPlane** [comment]
Thank you, I should have known as much and not to trust they hit the "Update" button. ;)
