### ISSUE TITLE
Character Page 404

### ISSUE THREAD

**Issue by thelastdragon** [danpaulson/swgoh.gg.public#52]
Hey there,

I created an account recently, but I attempt to view my account page it goes to a 404 error. When I attempt to update my profile and add details for account sync they also do not save. I can log in and use the rest of the site fine. My account name is tr33hugger.

Send a message to let me know what other information you need to troubleshoot this. I don't want to leave any details here.

Thanks.

**Comment by Ogskar** [comment]
I have the exact same issue. I cannot sync or view profile without 404 error.

**Comment by thelastdragon** [comment]
I just tried starting a new account and am having the exact same issue. Can we get some help here?

**Comment by Ogskar** [comment]
I found that copy and paste the player Id.
You need to I clude the line at the beginning of the I'd.

**Comment by scoot1585** [comment]
Sorry Dan and I both been busy, are you guys still having this issue?

**Comment by Ogskar** [comment]
I'm not having anymore issues.
Thank you

**Comment by Andokain** [comment]
I have the exact same issue. I cannot sync or view profile without 404 error.

**Comment by scoot1585** [comment]
what is your profile? 
is this a new account?
if not was your account working before?
if not a new account, have you made any changes recently?

Thanks for feedback, these hopefully will help me track it down

**Comment by Andokain** [comment]
My account Name is Andokain and it is a new account

**Comment by scoot1585** [comment]
Ah ok, found the issue.  Not a quick fix so I need to talk through options with Dan.  This is due to some code rework on the user areas to remove duplicated code.

**Comment by Andokain** [comment]
Ok

**Comment by danpaulson** [comment]
https://swgoh.gg/u/Andokain/

This should be resolved.

**Comment by thelastdragon** [comment]
Hey, thanks for checking back. I understand you guys are busy! 

Yes, this issue has also been corrected for me, thank you! 

Now when the delete feature comes out I'll remove the extra accounts I created to test, hehe.

Your efforts are greatly appreciated!

**Comment by Andokain** [comment]
Hey thanks for helping.
The Problem is fixed
