### ISSUE TITLE
New member - settings and sync do not save

### ISSUE THREAD

**Issue by V0l0** [danpaulson/swgoh.gg.public#54]
Hello, 

I am a new user and have been trying to set up my sync.
any changes i make on the settings page (including ally code and playerid), except for time zone, do not save.

**Comment by scoot1585** [comment]
Hmm, can you pm me your player id on here, or on reddit /u/czarbss so I can try it out

**Comment by scoot1585** [comment]
I am going to assume this was one of the issues we had related to character 404s and such.  If you are still having issues, feel free to reopen and provide more info.
