### ISSUE TITLE
Capital Ship Stats 

### ISSUE THREAD

**Issue by last1jedi** [danpaulson/swgoh.gg.public#55]
Capital Ship stats seem to be below than what is being seen in arena on 7* ships. I suspect the stats assume G11 max crew

**Comment by scoot1585** [comment]
Are they still below?  We upgraded the ships to be 7* capital ships for max stats this last weekend.

**Comment by scoot1585** [comment]
I am going to close this as I believe we do have correct stats now.  If you can provide any extra info to show us where we differ, we can reopen this issue
