### ISSUE TITLE
Crew stat contribution multipliers

### ISSUE THREAD

**Issue by jrmlry83** [danpaulson/swgoh.gg.public#59]
Crew stat contribution multipliers seem to include the max ship multiplier (1.5x) already.

Formula for a ship stat: crew_rating * ship_multiplier * crew_stat_contribution

For TFP speed:
crew_stat_contribution = 0.00361416
ship multiplier = 1.5
crew_rating (max) = 16948

Speed from crew contribution = 16948 * 1.5 * 0.00361416 = 91.88.

Actual max value = 61 (from in-game and from side stats table)

**Comment by scoot1585** [comment]
crew rating != crew power (or max unit power)

https://www.reddit.com/r/SWGalaxyOfHeroes/comments/5f433c/explanation_of_how_ship_stats_work_and_data_tables/ 

and more specifically where I talk about this https://www.reddit.com/r/SWGalaxyOfHeroes/comments/5f433c/explanation_of_how_ship_stats_work_and_data_tables/dahowgf/
