### ISSUE TITLE
Request: Add optional contact detail fields to our player profiles

### ISSUE THREAD

**Issue by SnakesOnAPlane** [danpaulson/swgoh.gg.public#6]
Enhancement Request

Please consider adding "optional" contact detail fields to our player profiles, allowing us to input our Discord, Line, Reddit, etc, usernames/IDs, ultimately making ourselves more easily findable. 

The majority come here looking for other players, and modeling it as a directory of sorts would help players contact others who also want to be found.

Thank you kindly for any consideration.

**Comment by scoot1585** [comment]
added in the feature to profiles https://www.reddit.com/r/SWGalaxyOfHeroes/comments/6brapc/a_swgohgg_request_please_put_a_space_in_our/
