### ISSUE TITLE
Arena Average

### ISSUE THREAD

**Issue by Iwan55555** [danpaulson/swgoh.gg.public#60]
Please find a solution for guild on top trying to cheat/manipulate the rankings by hiding their lower ranked profiles ( as swapping members during TB is not realistic)

for example 
![naamloos](https://user-images.githubusercontent.com/32458020/31503229-688bf20c-af6f-11e7-98c5-50bf320b21a0.png)

seeing guilds . hiding profiles to beat the rankings is not fair and should be penalised, all of the top guilds have public swgoh.gg accounts. as its even a must by most.. You guys know that urself.

The leaderboard for Rancor/Haat doesnt say anything and well we do respect how you work with that top200 to stay in there, so our numbers are being updated nonstop..

So we would suggest for every profile not showing up on averag arena ranking give them the average of 50 for the missing profile.. so it discourages Guild to use this method to manipulate the rankings

**Comment by danpaulson** [comment]
We are working on a 'Power Ranking' for guilds, that takes into consideration GP, Arena and Raid. This would be where we penalize guilds for not having full rosters on .GG.

On top of that, we will soon be disabling private profiles, so that should fix that as well.
