### ISSUE TITLE
Yoda is shown as a rebel

### ISSUE THREAD

**Issue by ronoaldo** [danpaulson/swgoh.gg.public#61]
Yoda is consistently doing some photobomb when I try to capture a picture of units tagged rebel, both here:

https://swgoh.gg/characters/f/rebel/

![captura de tela de 2017-10-13 12-30-38](https://user-images.githubusercontent.com/564649/31553921-5da60154-b012-11e7-8f00-0e54ea788d3d.png)

... and here:

https://swgoh.gg/u/ronoaldo/collection/?f=rebel

![captura de tela de 2017-10-13 12-29-55](https://user-images.githubusercontent.com/564649/31553877-3f9f8bf8-b012-11e7-96da-76c6a6a4085a.png)

"Young" Yoda seems now envy of all attention Hermit Yoda is getting, perhaps that is the case? :thinking:

**Comment by scoot1585** [comment]
lol damnit.  I keep squashing a few of these.  But didn't do a large pass to completely elminate the problem.  I'll fix these up as the problem relates to using a "non-visible" category.  And it isn't really even meant to be "Rebel", that is just what CG called the short version of some subgroupings that aren't player visible.

![image](https://user-images.githubusercontent.com/3346556/31559270-a99aa328-b015-11e7-906a-359e93c4c5f7.png)

**Comment by scoot1585** [comment]
This is fixed

**Comment by ronoaldo** [comment]
Nice! Thank you very much!
