### ISSUE TITLE
Farmboy Luke in Guild Events Store

### ISSUE THREAD

**Issue by Gregen11** [danpaulson/swgoh.gg.public#62]
Hey, I just noticed that Luke Skywalker (Farmboy) is missing from the Guild events store.

I've attached an image showing him in there.

![lukeguildevents](https://user-images.githubusercontent.com/8518536/31580224-3cc8204c-b117-11e7-902f-488b5c1ed505.png)

**Comment by scoot1585** [comment]
Added. thanks for letting us know.  These ones rely on community data since they rotate :(
