### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by alannewton** [danpaulson/swgoh.gg.public#64]
I’ve been trying to sync for the last few hours; button POSTs but no update is performed. “Last update” now showing one day ago. /u/suizid

**Comment by DilatoryCheetah** [comment]
It has been 2 days since my profile has been sync'd.  Spot checking my guild mates, it looks most of them also have not been sync'd for 1-2 days.

**Comment by danpaulson** [comment]
Thanks for bringing this up. It seems as though we have run out of space on our DB. We'll need to look at the data and probably refactor a good deal of things to get this back in shape.

**Comment by scoot1585** [comment]
millions and millions of rows...ugh :(

**Comment by Dblade21** [comment]
I take it this is why our guild page hasn't updated to remove the players we removed from the guild?

**Comment by DilatoryCheetah** [comment]
My profile now shows that it has sync'ed, but when I check on my individual units, they still show stale data.  For example, it shows that my Tarkin is only G8, but I have upgraded him to G10.  It shows mods on my Phoenix units, but I have moved them to other characters.

**Comment by Wollfast** [comment]
my profile also shows as updated, but it doesnt change my arena squad, the gear or the mods i have moved, are you already working on this ? i have 2 days since im with this issue

**Comment by alannewton** [comment]
Dan - just noticed your intent to move to elastic; hit me up if you need help. Last implementation I did was for amnesty.org, well versed in it.

**Comment by sebagr** [comment]
Hi, I'm new here and I'm getting "Player ID not found. Please ensure you typed it correctly" when I try to sync. Is this related to this issue? If it is, it would be a good thing to update the error message now, at least, because I keep trying and trying without success. If it's not related, can someone point me in the right direction? I've checked I don't have any confusing characters like O vs 0, or I vs l. Thanks!

**Comment by danpaulson** [comment]
@sebagr did you use the tool to look up your ID?

https://swgoh.gg/id-help/

**Comment by sebagr** [comment]
Yes, I did and it can't find it. Is there any way in which I could troubleshoot this any further?
