### ISSUE TITLE
Tie Pilot not listed in fleet store

### ISSUE THREAD

**Issue by Volnon** [danpaulson/swgoh.gg.public#67]
Hey; just mentioning that I don't see the Tie Pilot in the list of characters available from Fleet Shipments. I included a picture of him in my fleet store.

![screenshot_2017-10-20-18-28-47](https://user-images.githubusercontent.com/32970288/31844374-49b14b36-b5c6-11e7-9dfb-6e025d00c7e8.png)

**Comment by scoot1585** [comment]
Thanks for the report, I updated. If you know of any lists that has all the new characters offered, I will gladly update it with the new grouping display we have.
