### ISSUE TITLE
Exposing shards farmed towards unearned star level

### ISSUE THREAD

**Issue by ThariusDawnbreaker** [danpaulson/swgoh.gg.public#71]
I am attempting to create a farming optimization page that uses swgoh.gg data (hell I don't care, once it's made you can have it and tweak it).

It would make the optimization calculation more accurate if the number of shards farmed towards an unfinished star level was exposed and would avoid having people manually entering data.

I suggest that this information be added to the div that contains the class="star-inactive" attribute as a hover or an alt.  This way it would appear on the swgoh.gg site if a user hovers their grey star.  If it is simply presented as an amalgamated total /330, that's still workable.

Thank you

**Comment by danpaulson** [comment]
Good question, and one we get a lot so I added an FAQ!

https://github.com/danpaulson/swgoh.gg.public#faq

**Comment by ThariusDawnbreaker** [comment]
Well ... shit.  :)

Thanks for the reply Dan, I originally reddit mailed you but had noticed
you had referred someone else to the github suggestions page so I followed
suit.

I think what I'll do is use your exposed data and offer to allow the user
to input their shard totals for more accurate estimates, then if they're
really close on time for an event they can min/max it by hand.

Best,
Steve
