### ISSUE TITLE
Players leaving the guild, doesnt get removed

### ISSUE THREAD

**Issue by jfaldanam** [danpaulson/swgoh.gg.public#73]
Some members left our guild while servers where down, now we have 52 members according to swgoh.gg, which is breaking some of the tools used for TB management. We cant force players to refresh their account as we are no longer in contact with them. There is any other way of removing them of the guild? Maybe add officer ranks with posibility to force updates on members of the guild?

**Comment by danpaulson** [comment]
Going to need links to investigate.

We have no data on who is or isn't an officer, and no intention to manage that ourselves (would be borderline impossible).

**Comment by jfaldanam** [comment]
This is our guild: https://swgoh.gg/g/25027/rebel-force-lothal/
These are some guys that have left the guild in the last 5 days:
https://swgoh.gg/u/orions/
https://swgoh.gg/u/dakk/

Can you extract the guild rank from the same data you extracct the rest of your info from or it is something outside your posibilities?

I completly agree with this being something you cant manage yourselves

Thanks for the quick answer.

**Comment by danpaulson** [comment]
No guild info in our data unfortunately. We've asked CG to help, not sure if that'll ever happen.

I think I see the issue, will see what's causing it.
