### ISSUE TITLE
Innacurate guild members on swgoh.gg

### ISSUE THREAD

**Issue by Meredial** [danpaulson/swgoh.gg.public#744]
My guild has a member on our guild members list who is no longer in guild and one of our current members doesn't show up. https://swgoh.gg/g/23967/tuppacas-deathfall/

**Comment by scobenes** [comment]
We are actually working on something that should solve this reoccurring problem very soon.  But for right now I synced your guild and should be back to expected people showing up.

**Comment by Meredial** [comment]
Thank you!
