### ISSUE TITLE
Can't retrieve data from API with coreapi

### ISSUE THREAD

**Issue by alexgarciavila** [danpaulson/swgoh.gg.public#746]
When I run "coreapi get https://swgoh.gg/api/" I get all the html of the page instead of the corresponding dictionaries.
Following your documentation, when I run "coreapi action abilities list" I get an error that the "abilities" key is not found

For example if I use another website https://treeherder.mozilla.org/docs/ it works fine. And if I use for example "coreapi action changelog list", it works.

Is there a problem with your api?

Thanks for your work

![20220220-1575](https://user-images.githubusercontent.com/55148944/154842407-0d8d32d8-2af9-4914-8663-8497499a87ad.png)

![20220220-1577](https://user-images.githubusercontent.com/55148944/154842419-9d1a676b-db54-46a0-9e29-fb777b941b74.png)

**Comment by alexgarciavila** [comment]
In python, following your documentation
(import coreapi statement is at the beginning of the python file and the "pip install coreapi" was installed)

![20220220-1584](https://user-images.githubusercontent.com/55148944/154842980-d36fcf11-5803-459f-9201-97ccf10ba311.png)


![20220220-1579](https://user-images.githubusercontent.com/55148944/154842855-d783190f-5725-469a-bf15-b92118247145.png)

![20220220-1581](https://user-images.githubusercontent.com/55148944/154842860-d5df3166-f188-4d94-bb12-d57d4df2b9d2.png)

**Comment by alexgarciavila** [comment]
More info:

When i try to push the "interact" button and "send request" i got an undefined response

![20220220-1586](https://user-images.githubusercontent.com/55148944/154843740-18b410d8-e605-43ec-a05d-41def4c61a95.png)

**Comment by danpaulson** [comment]
The actions are the additional url paths available. Example: https://swgoh.gg/api/abilities/

The root /api/ is just documentation so wouldn't respond with anything useful for coreapi.

**Comment by danpaulson** [comment]
Actually I see your issue (unfamiliar with coreapi). We provide the API routes but are not currently supporting coreapi.

**Comment by alexgarciavila** [comment]
Ooh, thank you for your quick response.
I will work on it.

Great job, and thanks a lot.
