### ISSUE TITLE
Feature Request: GAC Ship Meta Report

### ISSUE THREAD

**Issue by playnwin** [danpaulson/swgoh.gg.public#748]
While ship metas can be kind of stale and "solved", there's still some unknowns regarding ideal lineups or the win rates for specific matchups. Since ship results are viewable in GAC history, it seems like there should be enough info for the GAC Meta Ship report. This would be able to provide information for existing fleets, and should be able to help identify the meta impact of new ships as they're added to the game.

**Comment by scobenes** [comment]
This has been added, so closing this issue
