### ISSUE TITLE
Guild Name Changed

### ISSUE THREAD

**Issue by ThenanJeth** [danpaulson/swgoh.gg.public#75]
I'm the guildleader for the guild Council of Jeth. We used to be called Credits Rule Everything before I took over. How do we get our correct guild name to show up on swgoh.gg? It still shows our old name, and that's been changed now for over a year.

**Comment by danpaulson** [comment]
What is the url of your guild?

**Comment by ThenanJeth** [comment]
https://swgoh.gg/g/3711/credits-rule-everything/

Our original guildleader disappeared over a year ago, and I took over by contacting CG and they made me the GL and changed the name to Council of Jeth.
