### ISSUE TITLE
All ships' crew ability is missing on their pages

### ISSUE THREAD

**Issue by azgo** [danpaulson/swgoh.gg.public#753]
Hey there,

Just found that all ships' crew ability is missing on their pages.
https://swgoh.gg/ships/finalizer/ - Two steps ahead
https://swgoh.gg/ships/kylo-rens-command-shuttle/ - All 3: Surprise Raid & Strike Team & Zeal of the FO
https://swgoh.gg/ships/tie-silencer/ - Frenzied Rage
https://swgoh.gg/ships/hounds-tooth/ - Trandoshan Barricade
etc, etc

Please check, it seems a general misconfig for all ships.

Thank you!

Brgds,

**Comment by scobenes** [comment]
this happens sometimes if we run commands and dont run full import.  these should all be back. thanks for reporting

**Comment by azgo** [comment]
Thank you!!
