### ISSUE TITLE
Some mods are not correct

### ISSUE THREAD

**Issue by birrut** [danpaulson/swgoh.gg.public#754]
One of my character's mods is not correct. It looks like maybe it still has the mod stats before I sliced it? I now have a blue 6dot mod, but swgoh.gg shows a 5dot mod. Here is the page with the wrong mod:
https://swgoh.gg/p/482764294/characters/chewbacca
The diamond mod is the wrong one. I've had this mod on him for over a week. 
![Screenshot_20220519-191704](https://user-images.githubusercontent.com/104339521/169435680-36836275-69f3-400c-a7df-8e41c248e673.jpg)

**Comment by danpaulson** [comment]
I believe this should be fixed now.
