### ISSUE TITLE
5 lvl SEE guide is bug 

### ISSUE THREAD

**Issue by Sebasyusseff** [danpaulson/swgoh.gg.public#755]

**Comment by Sebasyusseff** [comment]
I already spend like 140 energy try that do the lvl and can’t enter, just try charge and nothing happen…

**Comment by hirogolf** [comment]
I lost 140 tickets.

**Comment by scobenes** [comment]
we are not affiliated with CG, we just run a website about the game.  go through the game and there is a "Help" button in the settings popup
