### ISSUE TITLE
Character and Mod Data Missing for Some Players

### ISSUE THREAD

**Issue by KalSarkon** [danpaulson/swgoh.gg.public#76]
Going through my guild mates, I can see the character and mod data for some players, but others come up missing.  For example, data for myself shows up fine (https://swgoh.gg/u/kal_sarkon/collection/).  But when I look at this players' character page (https://swgoh.gg/u/anjinsan/collection/), it shows the character icons, but does not show any data (gear/level/stars) for the characters.  Similar thing with mods.  Mods show for https://swgoh.gg/u/kal_sarkon/mods/, but for https://swgoh.gg/u/anjinsan/mods/ it shows 0 mods.

I also notice that our guild list shows players that left maybe a week ago, but it looks like that bug has already been reported.

**Comment by danpaulson** [comment]
anjinsan has not logged in for more than 30 days - we only sync players that have done so. We will be adding messaging to make this more visible.

**Comment by KalSarkon** [comment]
Actually Anjinsan logs in every day.   Here is a screenshot showing his participation in today's guild activity.
![image](https://user-images.githubusercontent.com/33123458/32074970-362da86e-ba69-11e7-9522-10bf164c5e26.png)

And that was only one example.  Here are some more examples of active players who have broken character pages. 
https://swgoh.gg/u/lasoleair/collection/
https://swgoh.gg/u/dryads2/collection/
https://swgoh.gg/u/mac40/collection/
https://swgoh.gg/u/xodiack/collection/
https://swgoh.gg/u/joslecosar/collection/
I didn't check everyone's page.  I would estimate that about a third of the pages are broken.  Here is a screenshot showing daily activity.  You can see that Xodiack and Lasoleair have been active.

**Comment by danpaulson** [comment]
I uh, I meant the site. We don't run the game, so anything we talk about logging in will be contextual to SWGOH.GG.
