### ISSUE TITLE
Freezes

### ISSUE THREAD

**Issue by Shrake34** [danpaulson/swgoh.gg.public#766]
The ongoing freeze issue has gotten worse on my device instead of better after the update that was supposed to fix it!!! I'm not sure how to send in data yet but I will asap

**Comment by scobenes** [comment]
we are not associated with EA/CG, you need to open support tickets on their support sites

https://help.ea.com/en/help/star-wars/star-wars-galaxy-heroes/how-to-contact-support-for-star-wars-galaxy-of-heroes/
