### ISSUE TITLE
Swgoh Unit Search had been broken

### ISSUE THREAD

**Issue by Bouggaggga** [danpaulson/swgoh.gg.public#77]
Hi,
After one of the last week updates Collection Sync had been broken for all our guild members. Unit search does not show their units anymore. 
It is helpful to login to swgoh.gg, open Settings & Sync and click Update Profile button there. However it is not a deal. Is it possible to update all profiles somehow automatically from server's side?

**Comment by spuljko** [comment]
Same here. In units search, one players is always missing. In his collection page all characters are displayed.

**Comment by danpaulson** [comment]
Please provide links so we can look in to this. We can't magically know who you are on the site.
