### ISSUE TITLE
api/abilities/  no longer supports zeta or omicron filters

### ISSUE THREAD

**Issue by driderdesigns** [danpaulson/swgoh.gg.public#779]
The abilities API used to allow optional URL params to restrict the data being returned.
The filters worked a few days ago; I noticed them broken last night.

https://swgoh.gg/api/abilities/                               STILL WORKS
https://swgoh.gg/api/abilities/?is_zeta=true          BROKEN
https://swgoh.gg/api/abilities/?is_omicron=true   BROKEN

Filtering on either ability type now returns:
{"data":null,"message":"Server Error"}

**Comment by scobenes** [comment]
sorry about that.  its fixed

**Comment by driderdesigns** [comment]
Damn, you are like FAST fast!  Thanks for the assist!!

**Comment by driderdesigns** [comment]
GL Ultimate abilities are being returned by both filters, they're in each list twice actually.

https://swgoh.gg/api/abilities/?is_omicron=true   returns this, twice.  I can add a prop check in code, but figure you might want to look on your end?

 {
	"base_id": "ultimateability_supremeleaderkyloren",
	"ability_id": "ultimateability_supremeleaderkyloren",
	"name": "Depths of Rage",
	"image": "https://game-assets.swgoh.gg/tex.ability_kyloren_tros_ultimate.png",
	"url": "//swgoh.gg/characters/supreme-leader-kylo-ren/",
	"tier_max": 1,
	"is_zeta": false,
	"is_omega": false,
	"is_omicron": false,
	"is_ultimate": true,

**Comment by scobenes** [comment]
Ah yea, I don't really use these filters for anything, so I didn't test something I changed super closely.  Fixed a logic issue and I think it should be back to normal now

**Comment by driderdesigns** [comment]
Solid!  Sounds like may day-to-day LOL.

I've got a roster progress site that tracks GL progress, Zetas, Omicrons, and meta teams.
https://swgoh.driderdesigns.com/

Thanks again!
