### ISSUE TITLE
guild name different

### ISSUE THREAD

**Issue by SoloHan1001** [danpaulson/swgoh.gg.public#78]
Hello. I am one of the officers in the guild Dacii Liberi Mists. The guild name was changed a couple of months ago in the game, but on swgoh.gg it remained as before (Dacii Liberi Genesis). 
Is there a possibility to appear with the real name: Dacii Liberi Mists 
https://swgoh.gg/g/18985/dacii-liberi-genesis/

**Comment by SoloHan1001** [comment]
No, we are not in top 200 and never been there :)

Brindusa Scheaua

Pe 27 oct. 2017 5:57 p.m., "Dan Paulson" <notifications@github.com> a scris:

Have you been in the top 200 / Leaderboard?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/danpaulson/swgoh.gg.public/issues/78#issuecomment-339995405>,
or mute the thread

**Comment by SoloHan1001** [comment]
Really, you closed my topic? I was expecting an answer. Only top 200 are important, or what?!

**Comment by danpaulson** [comment]
I made a megathread for these issues. We only get the top 200 guild data from the game. Go bitch at CG, we do this for free.
