### ISSUE TITLE
Character and Mod Data missing for Active Players  

### ISSUE THREAD

**Issue by KalSarkon** [danpaulson/swgoh.gg.public#79]
I posted this earlier and it was marked closed with the note that the player whose page I referenced was not active.  But the player _is active_.  Here is a screenshot from today's guild activity showing that Anjinsan is contributing:
![image](https://user-images.githubusercontent.com/33123458/32075339-8393e680-ba6a-11e7-98d6-5be0184b65ce.png)

But his character page - https://swgoh.gg/u/anjinsan/collection/ - has no data for the characters.
![image](https://user-images.githubusercontent.com/33123458/32075390-b266810c-ba6a-11e7-84ad-077b601e447d.png)

And here is his arena ranking, which shows him active through 18 October.  He has been active since, it apparently just stopped syncing then.
![image](https://user-images.githubusercontent.com/33123458/32075704-9554b146-ba6b-11e7-858e-7893b7c2a36f.png)

Also, there are many in our guild with the same problem.  Here are some more examples.  All are active players.  All have blank character pages.  And judging by their arena rank on swgoh.gg, all stopped syncing on 18 October.
https://swgoh.gg/u/lasoleair/collection/
https://swgoh.gg/u/dryads2/collection/
https://swgoh.gg/u/mac40/collection/
https://swgoh.gg/u/xodiack/collection/
https://swgoh.gg/u/joslecosar/collection/

Original post:

> Going through my guild mates, I can see the character and mod data for some players, but others come up missing. For example, data for myself shows up fine (https://swgoh.gg/u/kal_sarkon/collection/). But when I look at this players' character page (https://swgoh.gg/u/anjinsan/collection/), it shows the character icons, but does not show any data (gear/level/stars) for the characters. Similar thing with mods. Mods show for https://swgoh.gg/u/kal_sarkon/mods/, but for https://swgoh.gg/u/anjinsan/mods/ it shows 0 mods.
> 
> I also notice that our guild list shows players that left maybe a week ago, but it looks like that bug has already been reported.

And the reply:
> anjinsan has not logged in for more than 30 days - we only sync players that have done so. We will be adding messaging to make this more visible.

**Comment by fheider** [comment]
active player = active in swgoh
no login at swgoh for 30 days = no updates anymore

the solution:
anjinsan should login at swgoh.gg and sync his profile and then all toons are up to date.

**Comment by KalSarkon** [comment]
Thanks!  That probably explains it.  Although for at least some of them, the login is broken.  I will see if I can get them to post here with details.
