### ISSUE TITLE
Characters dont appear when I Update Profile

### ISSUE THREAD

**Issue by AlKafir666** [danpaulson/swgoh.gg.public#80]
I can only see the last characters i made some modification, the others show all in gray: https://swgoh.gg/u/alkafir/

**Comment by AlKafir666** [comment]
@danpaulson why you close it? my profile is still buged

**Comment by danpaulson** [comment]
I created a megathread - https://github.com/danpaulson/swgoh.gg.public/issues/85

**Comment by AlKafir666** [comment]
ahhh ok, thx!
