### ISSUE TITLE
IP adress showing in my settings page.

### ISSUE THREAD

**Issue by jfaldanam** [danpaulson/swgoh.gg.public#81]
I just logged in and entered on my settings page (https://swgoh.gg/u/settings/), and in the middle of it my IP adress appears for no apparent reason. Is this intentional?
![capture](https://user-images.githubusercontent.com/22096907/32107630-7b627272-bb2f-11e7-9fae-613a26152640.PNG)

**Comment by danpaulson** [comment]
Some debug that got pushed out; removed now.
