### ISSUE TITLE
Thrawn's and Old Ben's descriptions contradict the real situation

### ISSUE THREAD

**Issue by Bouggaggga** [danpaulson/swgoh.gg.public#86]
Hi,
We found weird the situation when Thrawn uses his 2nd skill against Old Ben under taunt. 

We have the following descriptions of the skills:
Thrawn's: ...can't **gain** buffs...
Ben's: When this Taunt expires, Old Ben **gains** Taunt for one turn.

So:
When Thrawn uses his 2nd skill against Ben, Ben's Taunt has to be cancelled, and he is prohibited to gain new Taunt. 

But you can see this video: https://vk.com/video72357399_456239073 where Ben actually **REgains** Taunt. 
so, maybe it is wrong wording in Ben's description? Maybe it should be When this Taunt expires, Old Ben **restores(turns back, regains)** Taunt for one turn. So it is not gaining of a new buff but turning back an old one.

Or it is a bug. 
Please, explore. Because now it is really confusing and unexpected when Thrawn cannot cancel and prohibit this positive Old Ben's buff.

**Comment by danpaulson** [comment]
All data comes directly from the game - we do not manually curate or change any data, ever. If it is not working as intended, it is a bug, but it’s not fixable by us. Perhaps try the official forums?
