### ISSUE TITLE
Lost Player ID in my profile + Player ID Help

### ISSUE THREAD

**Issue by yannickthibault** [danpaulson/swgoh.gg.public#88]
I've have an account on swgoh.gg and my collection was there but it suddently dispear. My player ID is not there anymore and when I re-enter it, it doesn't work.

I've try the Player ID Help but it's not working, I enter my Ally Code + Player ID, I'm clicking on the button, the page reload and I don,t have any error message.

My user name is: yannickthibault
My user # in swgoh.gg is: 43036

**Comment by Eskaycee** [comment]
I'm also having this problem. I tried using the Player ID and the screen just loads after clicking submit with the same information on my screen, not stating if my player ID was correct or not. 

swgoh Username: Eskaycee
swgoh User#: 59322

**Comment by DesVega** [comment]
Same problem here too. Won’t recognize my player ID, and player ID lookup took doesn’t work either.

Username: DesVega
User #: 86501

**Comment by RugoseKohn** [comment]
Same problem for me as well and a couple of my guild mates.

Username: Rugose Kohn
User #: 57217

**Comment by Dargkar** [comment]
Same problem for me as well. My player ID doesn't contain any of the difficult characters, it worked 2 weeks ago. Now it won't recognise my player ID and all player information (arena rank, guild and character info) is missing.

Username: Dar Gkar
User #: 36908

**Comment by JTDMaster** [comment]
same here
user 145036

**Comment by vrbinjo** [comment]
same here
Username: vrbinjo
User # 92732

**Comment by samigh12** [comment]
Also me this happend yesterday
UserName: sami
User # 94335

**Comment by Lukebbb74** [comment]
Same here. Just happened. Can't re-input my ID (which I saved and working for > 1 year)
UseName: Lukeb74
User # : 5663

**Comment by ReTRoBuTioN54** [comment]
I have the same problem it wont reinput my game id
User name ReTRoBuTioN54
User#: 112073

**Comment by bobthesponge** [comment]
Same here

**Comment by zbytek** [comment]
I have the same problem
zbytek
User #:128490

**Comment by bjfails** [comment]
Same issue all my collection and syncs went away.
Herrbifi
User# 168970

**Comment by kokes712** [comment]
Exact same issue
Kokes712
#68803

**Comment by AndiSchn** [comment]
Same problem here, since early morning.

swgoh Username: AndiS
swgoh User#: 46834

**Comment by vitoonto** [comment]
I am having the same problem. My account is gone and I can't get my player id to work.
My user # is 1103. User name is vitoonto

**Comment by TheGrandolaPaca** [comment]
One more to the stack.
TheGrandolaPaca
#35774

**Comment by AlKafir666** [comment]
same here
AlKafir
#21898

**Comment by SANTAJEDI** [comment]
I'm also having this issue and it won't let me back in as well

**Comment by SANTAJEDI** [comment]
I'm also having this issue

SANTAJEDI
58709

Please resolve as quick as possible TB starts in less than 3 hrs.  Thankyou

**Comment by zerodotone** [comment]
Same here
crudetail
#61211

**Comment by Dingleschmitz** [comment]
Same here
Dingleschmitz
130848

**Comment by Vaexqua** [comment]
Snap :(

Vaexqua
33531

**Comment by NolaEliza** [comment]
Nola Eliza
#105271

**Comment by 55kjsmith** [comment]
Same here
55KyleKatarn
56851

**Comment by hurky** [comment]
Same Here 
Hurky
User #99490

**Comment by johtr** [comment]
Guildmate #73533 (tallen73) is having the same problem. Won't show his data or let him sync. Player Id tool not working either

**Comment by RutherfordDBrave** [comment]
Same Problem.
 RutherfordDBrave
User # 37003

**Comment by rwgrier** [comment]
Same here:

Username: SleepyBulldog
User #:  39621

**Comment by DurGoose** [comment]
Since yesterday my guild has lost about 12 members (including me the chief) who were trying to sync the account before the TB starts today. Our guild went from 54 million PG to 39. We cant sync our individual account anymore and our account is empty. What is wrong? What should we do? Can you give us a hint?
https://swgoh.gg/g/13826/rebellion-quebecoise/

**Comment by GungaGalunga** [comment]
Same problem for me as well and a couple of my guild mates.

Username: GungaGalunga04
 User #: 58946

**Comment by Natron1** [comment]
Yep, same here 
Beastmode24
user#45968

**Comment by Monrooe** [comment]
I have the same problem

Username: Monrooe
User #44835

**Comment by AlKafir666** [comment]
Now ID is working, but the sync is not working well, Only 20 characters appear (the ones i did some kind of modification lately)

**Comment by Cletus-swgoh** [comment]
Can confirm AlKafir666 findings. Player ID has been accepted. Only recently modded characters are present. GP and arena rank are accurate. Two of the characters shown are Nightsister Zombie and Nightsister Spirit. I haven't messed with them since the release day. Possible this issue is tied to changes/updates made around the end of October near this event.

**Comment by danpaulson** [comment]
Bots died last night, restarted now but it caused caching issues. We’ve turned force rebuild back on so future syncs should work.

**Comment by AlKafir666** [comment]
Works fine to me now :D

**Comment by TheGrandolaPaca** [comment]
Thnx for the quick fix

**Comment by RugoseKohn** [comment]
Still won’t sync my account

**Comment by samigh12** [comment]
Now is work but the Arena Battles statistic not appear

**Comment by AlKafir666** [comment]
@samigh12 you have to wait until your arena reset, and the statistic will be registered. But you will not get back your past statistic

**Comment by NolaEliza** [comment]
My account is still not syncing, no characters, no guild.  I waited for arena reset and dried again.
Nola Eliza
#105271

**Comment by mazurra** [comment]
Same for me ...

**Comment by Eskaycee** [comment]
My works now - I had to use the Player ID tool to properly decode mine and then it worked like a charm.

**Comment by mazurra** [comment]
my dosent .... 
                
              
               
                 
                  Dnia 3 listopada 2017 17:54 Eskaycee &lt;notifications@github.com&gt; napisał(a):
                 
                 
                   My works now - I had to use the Player ID tool to properly decode mine and then it worked like a charm.

**Comment by kaijusan** [comment]
My main account won't update. I cannot enter the ally code. 

I noticed that on my second account, my ally code is 'garbled'. I am afraid to update this account. 
![screen shot 2017-11-04 at 4 43 47 pm](https://user-images.githubusercontent.com/33381076/32409286-5e190248-c17f-11e7-8529-9560280c1808.png)

Its been about two to three days now. Any prospect for resolution? Thanks!

**Comment by Starkilla2ndFoundation** [comment]
I’m having the same problems with it dammit syncing and I am not able to view any of my mods or toons.  

Starkilla2ndFoundation 
#45135

**Comment by Darth1710** [comment]
Same problem, profile #23350

**Comment by greyfortlight** [comment]
I just signed up for the site and each time I try to add my Player ID, when I go back it has completely disappeared. This sounds like the same issue, but it also sounds like its been resolved for a lot of people.

**Comment by Tenda72** [comment]
hello
same issue for at least two weeks.
Impossible to sync.

id : Tenda72
user #52301

thx
