### ISSUE TITLE
Distinguish between hard and normal gear locations

### ISSUE THREAD

**Issue by offsky** [danpaulson/swgoh.gg.public#9]
On the gear page, it shows the locations where that item can be farmed, but it does not indicate if its a Hard level or a Normal level.

For example:
https://swgoh.gg/db/gear/103PrototypeSalvage/mk-2-zaltin-bacta-gel-prototype-salvage/
and
https://swgoh.gg/db/gear/092Salvage/mk-4-arakyd-droid-caller-salvage/

Both say "Light Side Battles: 6-D" but they are not farmable on the same node. One is Normal and the other is Hard.

Thanks!

**Comment by scoot1585** [comment]
ah, good catch. will add an indicator

**Comment by scoot1585** [comment]
updated on site finally!
