### ISSUE TITLE
Tapping next page on filtered mods page brings you to unfiltered mod stack.

### ISSUE THREAD

**Issue by wantowan2** [danpaulson/swgoh.gg.public#92]
The following url just takes you to my mods filtered for speed secondary. https://swgoh.gg/u/wantowan2/mods/?stat2_5=1

Short term fix. Add ability to choose # of results dialogue in settings.

*****ALSO: changing filter from a filtered mod page gives "mixed results". A combination of old and new. Since an update...

**Comment by vauge** [comment]
+1

**Comment by danpaulson** [comment]
This is now fixed.
