### ISSUE TITLE
Extract lifetime raid tickets for guild members

### ISSUE THREAD

**Issue by DilatoryCheetah** [danpaulson/swgoh.gg.public#93]
With the ongoing bug with daily raid tickets, is there any way that you can extract the lifetime raid tickets for all guild members so that we can track the daily tickets ourselves?

I know that we would need to be able to specify guild reset time in order for the numbers to make the most sense.

Is this possible?

**Comment by celsogbj** [comment]
Is it possible?

It is a pain in the ass for the guilds to keep track of individual daily tickets. If you can implement this it would be the most awesone feature. The best thing since slice bread.

**Comment by danpaulson** [comment]
Unfortunately it is not possible with the current data we get from CG.
